-- #*#*#*#*#*#*#**#*#*#*#**#*#*#*#*#*#**#*# POLICE  -- #*#*#*#*#*#*#**#*#*#*#**#*#*#*#*#*#**#*# 
Pol_Sivag_033
Sivagangai$123
-- Dashboard  ----------------------------------------------------------------------done-----------------

SELECT  
    O.ID,
    O.COMPLAINT_NAME,
    O.COMPLAINT_COPY,
    O.COMPLAINT_COPY_MIMETYPE,
    O.COMPLAINT_COPY_FILENAME,
    O.FIR_NO,
    O.DATE_OF_FIR,
    O.fir_attach,
    O.FIR_ATTACH_MIMETYPE,
    O.FIR_ATTACH_FILENAME,
    O.CHARGE_SHEET_YES_NO,
    COALESCE(TO_CHAR(O.CHARGE_SHEET_DATE, 'DD-Mon-YYYY'), '-') AS CHARGE_SHEET_DATE,
    O.CHILD_AGE,
    O.NAME_PARENT,
    O.WILLINGNESS_COMPENSATION,
    COALESCE(O.WHO_NAME, '-') AS WHO_NAME,
    COALESCE(O.WHO_RELATIONSHIP, '-') AS WHO_RELATIONSHIP,
    COALESCE(TO_CHAR(O.WHO_DATE, 'DD-Mon-YYYY'), '-') AS WHO_DATE,
    COALESCE(O.ACCOUNT_HOLDER_NAME, '-') AS ACCOUNT_HOLDER_NAME,
    COALESCE(O.ACCOUNT_NUMBER, '-') AS ACCOUNT_NUMBER,
    COALESCE(O.BANK_NAME, '-') AS BANK_NAME,
    COALESCE(O.BRANCH_NAME, '-') AS BRANCH_NAME,
    COALESCE(O.IFSC_CODE, '-') AS IFSC_CODE,
    O.DISTRICT_NAME,
    O.POL_STAT,
    O.YEAR_DAT,
    O.CHILD_GENDER,
    O.STATUS,
    O.CREATED_BY,
    O.CREATED_DATE,
    O.UPDATED_DATE,
    O.UPDATED_BY,
    O.CHILD_NAME,
    O.AGE,
    S.DISTRICT_NAME AS DS,
    CASE 
        WHEN O.REQUEST_STATUS = 'CO' THEN 'Paid'
        WHEN O.REQUEST_STATUS IN ('E', 'S', 'F1', 'C') THEN 'Pending'
        ELSE NULL
    END AS Payment_Status,
    CASE
        WHEN O.WILLINGNESS_COMPENSATION = 'No' THEN 'Not awarded'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AWARDED_YES = 'No' THEN 'Not awarded'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AWARDED_YES = 'Yes' AND A.PROCEED_INTERIM IS NULL THEN 'Pending'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AWARDED_YES = 'Yes' AND A.PROCEED_INTERIM IS NOT NULL THEN 'Disbursed'
        ELSE 'Pending'
    END AS Condition_Status,
    CASE
        WHEN C.FINAL IS NOT NULL THEN 'Orders passed'
        WHEN C.FINAL IS NULL THEN 'Pending Trail'
        ELSE 'Pending'
    END AS Condition_Status_1,
    CASE
        WHEN O.WILLINGNESS_COMPENSATION = 'No' THEN 'Not awarded'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND A.PROCEED_FINAL IS NULL THEN 'Pending'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND A.PROCEED_FINAL IS NOT NULL THEN 'Disbursed'
        ELSE 'Pending'
    END AS Condition_Status_2,
    COALESCE(C.INTERIM_AWARDED_YES, '-') AS INTERIM_AWARDED_YES,
    O.NAME_MEDICAL_INSTITUTION,
    O.COMPLAINT_MADE,
    O.DATE_REQUISITION_MEDICAL_EXAMINATION,
    O.DATE_OF_MEDICAL_EXAMINATION_VICTIM,
    O.DATE_OF_INTERIM
FROM 
    TNEGA_OVERALL_T_DUP O
INNER JOIN 
    TNEGA_JUDGE_LOGIN_T C ON O.ID = C.COURT_ID
INNER JOIN 
    TNEA_SUPERINTENDENT_T A ON O.ID = A.COURT_ID
INNER JOIN 
    SIGNUP_T S ON TRIM(O.POL_STAT) = TRIM(S.NAME)
WHERE  
    S.ID = :APP_EMPLOYEE_ID 
    AND TRIM(S.ROLE) IN ('Police')  
ORDER BY 
    O.UPDATED_DATE DESC;




-- When Click on Edit icon, It move to Another Page:
--1. Police Entry Form  ----------------------------------------------------------------------done-----------------
SELECT 
    ID,
    DISTRICT_NAME,
    POL_STAT,
    YEAR_DAT,
    FIR_NO,
    STATUS,
    CREATED_BY,
    CREATED_DATE,
    UPDATED_DATE,
    UPDATED_BY,
    SENT_TO,
    DATE_OF_FIR,
    CHILD_NAME,
    CHILD_AGE,
    AGE,
    NAME_PARENT,
    ACCOUNT_NUMBER,
    BANK_NAME,
    BRANCH_NAME,
    ACCOUNT_HOLDER_NAME,
    IFSC_CODE,
	FIR_ATTACH,
    FIR_ATTACH_MIMETYPE,
    FIR_ATTACH_FILENAME,
    COMPLAINT_NAME,
    CHARGE_SHEET_YES_NO,
    CHARGE_SHEET_DATE,
    WILLINGNESS_COMPENSATION,
	COMPLAINT_COPY,
    COMPLAINT_COPY_MIMETYPE,
    COMPLAINT_COPY_FILENAME,
    WHO_APPLYING,
    WHO_NAME,
    WHO_RELATIONSHIP,
    WHO_DATE,
    BANK_DETAILS,
    CHILD_GENDER,
    DATE_REQUISITION_MEDICAL_EXAMINATION,
    DATE_OF_MEDICAL_EXAMINATION_VICTIM,
    DATE_OF_INTERIM,
    NAME_MEDICAL_INSTITUTION,
    COMPLAINT_MADE
FROM 
    TNEGA_OVERALL_T_DUP
WHERE 
    ID = :P73_ID;


-- Having 2 Buttons (1. Cancel, 2. Submit)
-- When click on Cancel it move to Previous Page.
-- When click on Submit Button Running Below query:  
1.  
UPDATE TNEGA_OVERALL_T_DUP
SET   CHARGE_SHEET_YES_NO = :P73_CHARGE_SHEET_YES_NO, 
        CHARGE_SHEET_DATE = :P73_CHARGE_SHEET_DATE
WHERE ID = :P73_ID;
  
-- Court Entry Form:
select ID,
       TYPE,
	   COURT_FILE_DATE,
       INTERIM_ORDER_DATE,
       ORDER_NO,
       STATUS,
       CREATED_BY,
       CREATED_DATE,
       UPDATED_BY,
       UPDATED_DATE,
       YES_TYPE,
       REMARKS,
       COURT_ID,
       FIR_NO,
       FINAL_ORDER_DATE,
       JUDGEMENT,
       CHANGE_BANK_ACCOUNT,
       BAK_ACCOUNT,
       IFSC_CODE,
       BANK_NAME,
       BRANCH_NAME,
       ACCOUNT_NUMBER,
       REMARKS_BANK,
       INTERIM_AMOUNT,
       final_amount,
	   INTERIM,
	   INTERIM_ATTACH_MIMETYPE,
       INTERIM_ATTACH_FILENAME,
       FINAL,
	   FINAL_ATTACH_MIMETYPE,
       FINAL_ATTACH_FILENAME,
       NAME_OF_COURT,
       INTERIM_AWARDED_YES
  from TNEGA_JUDGE_LOGIN_T
  WHERE ID = :P73_ID;


-- Disbursal Status
select ID,
       COURT_ID,
       REMARKS,
       SIGNED_PROCEED,
       SIGNED_MIMETYPE,
       SIGNED_FILENAME,
       NEW_STATUS
  from TNEA_SIGNED_DOCUMNETS_T
WHERE ID = :P73_ID;  

  
-- Add New Case 
--1. Police Entry Form:
select DISTRICT_NAME,
       POL_STAT,
       YEAR_DAT,
       FIR_NO,
       STATUS,
       CREATED_BY,
       CREATED_DATE,
       UPDATED_DATE,
       UPDATED_BY,
       SENT_TO,
       DATE_OF_FIR,
       CHILD_NAME,
       CHILD_AGE,
       AGE,
       NAME_PARENT,
       ACCOUNT_NUMBER,
       BANK_NAME,
       BRANCH_NAME,
       ACCOUNT_HOLDER_NAME,
       IFSC_CODE,
	   FIR_ATTACH,
       FIR_ATTACH_MIMETYPE,
       FIR_ATTACH_FILENAME,
       COURT_FILE_NO,
       TYPE_OF_ORDER,
       INTERIM_DATE,
       FINAL_DATE,
       AMOUNT_OF_COMPENSATION,
	   COURT_ATTACH,
       COURT_ATTACH_MIMETYPE,
       COURT_ATTACH_FILENAME,
       COMPLAINT_NAME,
       REQUEST_STATUS,
       CHARGE_SHEET_YES_NO,
       CHARGE_SHEET_DATE,
       WILLINGNESS_COMPENSATION,
       INTERIM_YES,
       FINAL_YES,
	   COMPLAINT_COPY,
       COMPLAINT_COPY_MIMETYPE,
       COMPLAINT_COPY_FILENAME,
       WHO_APPLYING,
       WHO_NAME,
       WHO_RELATIONSHIP,
       WHO_DATE,
       BANK_DETAILS,
       ID,
       CHILD_GENDER,
       DATE_REQUISITION_MEDICAL_EXAMINATION,
       DATE_OF_MEDICAL_EXAMINATION_VICTIM,
       DATE_OF_INTERIM,
       NAME_MEDICAL_INSTITUTION,
       COMPLAINT_MADE
  from TNEGA_OVERALL_T_DUP  
  
-- Having 2 buttons 1. Cancel, 2. Submit:
-- When click on submit button Running Below query:
1.
INSERT INTO TNEGA_OVERALL_T_DUP (DISTRICT_NAME, POL_STAT, COMPLAINT_NAME, COMPLAINT_MADE, FIR_NO, DATE_OF_FIR, CHILD_GENDER, CHILD_AGE, AGE,NAME_PARENT, WILLINGNESS_COMPENSATION,
                                 WHO_APPLYING, WHO_NAME, WHO_RELATIONSHIP, WHO_DATE, BANK_DETAILS, ACCOUNT_HOLDER_NAME,  ACCOUNT_NUMBER, BANK_NAME, BRANCH_NAME,IFSC_CODE, 
								 CHARGE_SHEET_YES_NO, CHARGE_SHEET_DATE, NAME_MEDICAL_INSTITUTION, DATE_REQUISITION_MEDICAL_EXAMINATION, DATE_OF_MEDICAL_EXAMINATION_VICTIM,DATE_OF_INTERIM)
				          Values(:P50_DISTRICT_NAME, :P50_POL_STAT, :P50_COMPLAINT_NAME, :P50_COMPLAINT_MADE, :P50_FIR_NO, :P50_DATE_OF_FIR, :P50_CHILD_GENDER, :P50_CHILD_AGE, 
						         :P50_AGE,:P50_NAME_PARENT, :P50_WILLINGNESS_COMPENSATION, :P50_WHO_APPLYING, :P50_WHO_NAME, :P50_WHO_RELATIONSHIP, :P50_WHO_DATE, :P50_BANK_DETAILS, 
								 :P50_ACCOUNT_HOLDER_NAME,  :P50_ACCOUNT_NUMBER, :P50_BANK_NAME, :P50_BRANCH_NAME, :P50_IFSC_CODE, :P50_CHARGE_SHEET_YES_NO, :P50_CHARGE_SHEET_DATE, 
								 :P50_NAME_MEDICAL_INSTITUTION, :P50_DATE_REQUISITION_MEDICAL_EXAMINATION, :P50_DATE_OF_MEDICAL_EXAMINATION_VICTIM, :P50_DATE_OF_INTERIM);
2.
update TNEGA_OVERALL_T_DUP 
set request_status='E' 
WHERE ID=:P50_ID;
/*
3.
IF :P50_DOCS is not null then
UPDATE TNEGA_OVERALL_T_DUP
SET COMPLAINT_COPY = :P50_COMPLAINT_COPY,
    COMPLAINT_COPY_FILENAME = :P50_COMPLAINT_COPY_FILENAME,
	COMPLAINT_COPY_MIMETYPE = :P50_COMPLAINT_COPY_MIMETYPE
WHERE ID = :P50_ID;

4.
IF :P50_FIR is not null then
UPDATE TNEGA_OVERALL_T_DUP
SET FIR = :P50_FIR,
    FIR_ATTACH_FILENAME = :P50_FIR_ATTACH_FILENAME,
	FIR_ATTACH_MIMETYPE = :P50_FIR_ATTACH_MIMETYPE
WHERE ID = :P50_ID;
*/
5.
INSERT INTO TNEGA_JUDGE_LOGIN_T (COURT_ID)
                         VALUES (:P50_ID);

6.
INSERT INTO TNEA_SUPERINTENDENT_T (COURT_ID)
                           VALUES (:P50_ID);


  
  
-- 2. Court Entry Form
select ID,
       TYPE,
COURT_FILE_DATE,
       INTERIM_ORDER_DATE,
       ORDER_NO,
       STATUS,
       CREATED_BY,
       CREATED_DATE,
       UPDATED_BY,
       UPDATED_DATE,
       YES_TYPE,
       REMARKS,
       COURT_ID,
       FIR_NO,
       FINAL_ORDER_DATE,
       JUDGEMENT,
       CHANGE_BANK_ACCOUNT,
       BAK_ACCOUNT,
       IFSC_CODE,
       BANK_NAME,
       BRANCH_NAME,
       ACCOUNT_NUMBER,
       REMARKS_BANK,
       INTERIM_AMOUNT,
       final_amount,
	   INTERIM,
	   INTERIM_ATTACH_MIMETYPE,
       INTERIM_ATTACH_FILENAME,
	   FINAL,
	   FINAL_ATTACH_MIMETYPE,
       FINAL_ATTACH_FILENAME,
       NAME_OF_COURT,
       INTERIM_AWARDED_YES
  from TNEGA_JUDGE_LOGIN_T




-- 3. Disbursal Status  
SELECT 
    ID,
    STATUS,
    CREATED_BY,
    CREATED_DATE,
    UPDATED_BY,
    UPDATED_DATE,
	PROCEED_INTERIM,
    PROCEED_ATTACH_MIMETYPE,
    PROCEED_ATTACH_FILENAME,
    COURT_ID,
    SENIORITY_LEVEL,
    REMARKS,
    FIR_NO,
    COURT_FILE_NO,
	PROCEED_FINAL,
    NEFT_ATTACH_MIMETYPE,
    NEFT_ATTACH_FILENAME,
    CHANGE_BANK_ACCOUNT,
    NEW_STATUS,
    BAK_ACCOUNT,
    BANK_NAME,
    BRANCH_NAME,
    ACCOUNT_NUMBER,
    IFSC_CODE,
    REMARKS_BANK,
    ACC_HOLDER_NAME,
    FINAL_PAYMENT_STATUS,
    INTERIM_PAYMENT_STATUS
FROM 
    TNEA_SUPERINTENDENT_T;


-- #*#*#*#*#*#*#**#*#*#*#**#*#*#*#*#*#**#*#    Court  -- #*#*#*#*#*#*#**#*#*#*#**#*#*#*#*#*#**#*# 
-- Dashboard:
SELECT 
    O.ID,
    O.DISTRICT_NAME,
    O.CHILD_GENDER,
    O.POL_STAT,
    O.COMPLAINT_NAME,
    O.DATE_OF_FIR,
    O.FIR_NO,
    C.COURT_FILE_DATE,
	O.COMPLAINT_COPY,
    O.COMPLAINT_COPY_MIMETYPE,
    O.COMPLAINT_COPY_FILENAME,
    O.NAME_PARENT,
    O.WILLINGNESS_COMPENSATION,
    COALESCE(O.WHO_NAME, '-') AS WHO_NAME,
    COALESCE(O.WHO_RELATIONSHIP, '-') AS WHO_RELATIONSHIP,
    COALESCE(TO_CHAR(O.WHO_DATE, 'DD-Mon-YYYY'), '-') AS WHO_DATE,
    COALESCE(O.ACCOUNT_NUMBER, '-') AS ACCOUNT_NUMBER,
    COALESCE(O.BANK_NAME, '-') AS BANK_NAME,
    COALESCE(O.BRANCH_NAME, '-') AS BRANCH_NAME,
    COALESCE(O.ACCOUNT_HOLDER_NAME, '-') AS ACCOUNT_HOLDER_NAME,
    COALESCE(O.IFSC_CODE, '-') AS IFSC_CODE,
    COALESCE(C.ORDER_NO, '-') AS ORDER_NO,
    COALESCE(O.CHARGE_SHEET_YES_NO, '-') AS CHARGE_SHEET_YES_NO,
    COALESCE(TO_CHAR(O.CHARGE_SHEET_DATE, 'DD-Mon-YYYY'), '-') AS CHARGE_SHEET_DATE,
    C.INTERIM_ORDER_DATE,
    C.FINAL_AMOUNT,
    C.INTERIM_AMOUNT,
    C.FINAL_ORDER_DATE,
    COALESCE(C.TYPE, '-') AS TYPE,
    COALESCE(C.JUDGEMENT, '-') AS JUDGEMENT,
    CASE 
        WHEN O.REQUEST_STATUS = 'CO' THEN 'Disposed'
        WHEN O.REQUEST_STATUS IN ('E', 'S', 'F1', 'C') THEN 'Pending'
        ELSE NULL
    END AS REQUEST_STATUS,
   (CURRENT_DATE - O.CHARGE_SHEET_DATE) AS DURATION,
    COALESCE(C.NAME_OF_COURT, '-') AS NAME_OF_COURT,
    O.INTERIM_YES,
    O.FINAL_YES,
    C.ID AS CID,
    C.INTERIM,
    C.FINAL,
    A.PROCEED_INTERIM AS PROCEED_INTERIM,
    A.PROCEED_FINAL AS PROCEED_FINAL,
    A.INTERIM_PAYMENT_STATUS,
    A.FINAL_PAYMENT_STATUS,
    A.NEW_STATUS,
    A.ID AS AID,
    C.INTERIM,
	C.FINAL,
    CASE
        WHEN O.WILLINGNESS_COMPENSATION = 'No' THEN 'Not awarded'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AWARDED_YES = 'No' THEN 'Not awarded'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AWARDED_YES = 'Yes' AND A.PROCEED_INTERIM IS NULL THEN 'Pending'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AWARDED_YES = 'Yes' AND A.PROCEED_INTERIM IS NOT NULL THEN 'Disbursed'
        ELSE 'Pending'
    END AS Condition_Status,
    CASE
        WHEN C.FINAL IS NOT NULL THEN 'Orders passed'
        WHEN C.FINAL IS NULL THEN 'Pending Trail'
        ELSE 'Pending'
    END AS Condition_Status_1,
    CASE
        WHEN O.WILLINGNESS_COMPENSATION = 'No' THEN 'Not awarded'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND A.PROCEED_FINAL IS NULL THEN 'Pending'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND A.PROCEED_FINAL IS NOT NULL THEN 'Disbursed'
        ELSE 'Pending'
    END AS Condition_Status_2,
    COALESCE(C.INTERIM_AWARDED_YES, '-') AS INTERIM_AWARDED_YES,
    O.NAME_MEDICAL_INSTITUTION,
    O.COMPLAINT_MADE,
    O.DATE_REQUISITION_MEDICAL_EXAMINATION,
    O.DATE_OF_MEDICAL_EXAMINATION_VICTIM,
    O.DATE_OF_INTERIM
FROM 
    TNEGA_OVERALL_T_DUP O
    INNER JOIN TNEGA_JUDGE_LOGIN_T C ON O.ID = C.COURT_ID
    INNER JOIN TNEA_SUPERINTENDENT_T A ON O.ID = A.COURT_ID
    INNER JOIN SIGNUP_T S ON TRIM(O.DISTRICT_NAME) = TRIM(S.DISTRICT_NAME)
WHERE  
    -- S.ID = :APP_EMPLOYEE_ID 
   TRIM(S.ROLE) IN ('Court') 
    AND O.REQUEST_STATUS IN ('E', 'S', 'F1', 'C')
ORDER BY 
    O.UPDATED_DATE DESC;


SELECT * FROM public.signup_t;
   
-- When Click on Edit button it move to concrn Form Page:
P53_ID			#ID#
P53_ID_1		#CID#	
P53_COURT_ID	#ID#
P53_COURT_ID_1	#ID#	
P53_ID_2		#AID#

-- 1. Police Entry Details
select ID,
       DISTRICT_NAME,
       POL_STAT,
       YEAR_DAT,
       FIR_NO,
BANK_DETAILS,
       STATUS,
       CREATED_BY,
       CREATED_DATE,
       UPDATED_DATE,
       UPDATED_BY,
       SENT_TO,
       DATE_OF_FIR,
       CHILD_NAME,
       CHILD_AGE,
       AGE,
       NAME_PARENT,
       ACCOUNT_NUMBER,
       BANK_NAME,
       BRANCH_NAME,
       ACCOUNT_HOLDER_NAME,
       IFSC_CODE,
	   FIR_ATTACH,
       FIR_ATTACH_MIMETYPE,
       FIR_ATTACH_FILENAME,
     COMPLAINT_NAME,
     CHARGE_SHEET_YES_NO,
     CHARGE_SHEET_DATE,
     WILLINGNESS_COMPENSATION,
	 COMPLAINT_COPY,
     COMPLAINT_COPY_MIMETYPE,
     COMPLAINT_COPY_FILENAME,
     WHO_APPLYING,
     WHO_NAME,
     WHO_RELATIONSHIP,
     WHO_DATE,
     REQUEST_STATUS,
       CHILD_GENDER,
       DATE_REQUISITION_MEDICAL_EXAMINATION,
       DATE_OF_MEDICAL_EXAMINATION_VICTIM,
       DATE_OF_INTERIM,
       NAME_MEDICAL_INSTITUTION,
       COMPLAINT_MADE
  from TNEGA_OVERALL_T_dup
  WHERE ID = :P53_ID;


-- Court Entry Form
-- It have 2 Buttons (1.Cancel, 2. Submit)
select ID,
       TYPE,
       COURT_FILE_DATE,
       INTERIM_ORDER_DATE,
       ORDER_NO,
       FINAL_AMOUNT,
       AMOUNT_DEPOSIT,
       AMOUNT_DEPOSIT_NAME,
       DISBURSEMENT_CONDITION,
	   ATTACH,
       ATTACH_MIMETYPE,
       ATTACH_FILENAME,
       STATUS,
       CREATED_BY,
       CREATED_DATE,
       UPDATED_BY,
       UPDATED_DATE,
       YES_TYPE,
       REMARKS,
       COURT_ID,								--P53_COURT_ID
       FIR_NO,
       FINAL_ORDER_DATE,
       JUDGEMENT,
       CHANGE_BANK_ACCOUNT,
       BAK_ACCOUNT,
       IFSC_CODE,
       BANK_NAME,
       BRANCH_NAME,
       ACCOUNT_NUMBER,
       REMARKS_BANK,
       INTERIM_AMOUNT,
	   INTERIM,
 INTERIM_ATTACH_MIMETYPE,
       INTERIM_ATTACH_FILENAME,
	   FINAL,
 FINAL_ATTACH_MIMETYPE,
       FINAL_ATTACH_FILENAME,
       NAME_OF_COURT,
       INTERIM_AWARDED_YES
  from TNEGA_JUDGE_LOGIN_T
  WHERE P53_COURT_ID = :P1_ID;


-- When Click on Submit Button Running Below query:



1.
update TNEGA_OVERALL_T_DUP set
 IFSC_CODE=COALESCE(:P53_IFSC_CODE_1, :P53_IFSC_CODE),
 BANK_NAME= COALESCE(:P53_BANK_NAME_1, :P53_BANK_NAME), 
 BRANCH_NAME= COALESCE(:P53_BRANCH_NAME_1, :P53_BRANCH_NAME),
ACCOUNT_NUMBER= COALESCE(:P53_ACCOUNT_NUMBER_1, :P53_ACCOUNT_NUMBER),
ACCOUNT_HOLDER_NAME= COALESCE(:P53_BAK_ACCOUNT, :P53_ACCOUNT_HOLDER_NAME ),
request_status = 'S'
where id=:P53_COURT_ID;


2.
UPDATE TNEGA_OVERALL_T_DUP O
SET O.request_status = 'C'
WHERE O.ID = :P53_COURT_ID_1 
AND O.ID = (SELECT J.COURT_ID FROM TNEA_SUPERINTENDENT_T J 
            WHERE J.COURT_ID = :P53_ID 
			AND J.NEW_STATUS = 'Interim Order Status');


	
3.
IF :P53_INTERIM_AMOUNT IS NOT NULL AND  :P53_INTERIM_ORDER_DATE IS NOT NULL THEN
UPDATE TNEGA_JUDGE_LOGIN_T
SET ORDER_NO = :P53_ORDER_NO,
    COURT_FILE_DATE = :P53_COURT_FILE_DATE,
    NAME_OF_COURT = :P53_NAME_OF_COURT,
    INTERIM_ORDER_DATE = :P53_INTERIM_ORDER_DATE,
    INTERIM_AMOUNT = :P53_INTERIM_AMOUNT,
    JUDGEMENT = :P53_JUDGEMENT,
    TYPE = :P53_TYPE,
    CHANGE_BANK_ACCOUNT = :P53_CHANGE_BANK_ACCOUNT,
    INTERIM_AWARDED_YES = :P53_INTERIM_AWARDED_YES,
    BRANCH_NAME=:P53_BRANCH_NAME_1,
    BAK_ACCOUNT=:P53_BAK_ACCOUNT,
    IFSC_CODE=:P53_IFSC_CODE_1,
    ACCOUNT_NUMBER=:P53_ACCOUNT_NUMBER_1,
   BANK_NAME = :P53_BANK_NAME_1
WHERE COURT_ID = :P53_ID;
END IF;

4.
IF :P53_INTERIM_AMOUNT IS NULL AND  :P53_INTERIM_ORDER_DATE IS NULL THEN
UPDATE TNEGA_JUDGE_LOGIN_T
SET ORDER_NO = :P53_ORDER_NO,
    COURT_FILE_DATE = :P53_COURT_FILE_DATE,
    NAME_OF_COURT = :P53_NAME_OF_COURT,
    FINAL_AMOUNT = :P53_FINAL_AMOUNT,
    FINAL_ORDER_DATE = :P53_FINAL_ORDER_DATE, 
    JUDGEMENT = :P53_JUDGEMENT,
    TYPE = :P53_TYPE,
    CHANGE_BANK_ACCOUNT = :P53_CHANGE_BANK_ACCOUNT,
    INTERIM_AWARDED_YES = :P53_INTERIM_AWARDED_YES,
    BRANCH_NAME=:P53_BRANCH_NAME_1,
    BAK_ACCOUNT=:P53_BAK_ACCOUNT,
    IFSC_CODE=:P53_IFSC_CODE_1,
    ACCOUNT_NUMBER=:P53_ACCOUNT_NUMBER_1,
   BANK_NAME = :P53_BANK_NAME_1
WHERE COURT_ID = :P53_ID;
END IF;

5.
IF :P53_INTERIM_AMOUNT IS NULL AND  :P53_INTERIM_ORDER_DATE IS NOT NULL THEN
UPDATE TNEGA_JUDGE_LOGIN_T
SET ORDER_NO = :P53_ORDER_NO,
    COURT_FILE_DATE = :P53_COURT_FILE_DATE,
    NAME_OF_COURT = :P53_NAME_OF_COURT,
    INTERIM_ORDER_DATE = :P53_INTERIM_ORDER_DATE,
    INTERIM_AMOUNT = :P53_INTERIM_AMOUNT,
    JUDGEMENT = :P53_JUDGEMENT,
    TYPE = :P53_TYPE,
    CHANGE_BANK_ACCOUNT = :P53_CHANGE_BANK_ACCOUNT,
    INTERIM_AWARDED_YES = :P53_INTERIM_AWARDED_YES,
    BRANCH_NAME=:P53_BRANCH_NAME_1,
    BAK_ACCOUNT=:P53_BAK_ACCOUNT,
    IFSC_CODE=:P53_IFSC_CODE_1,
    ACCOUNT_NUMBER=:P53_ACCOUNT_NUMBER_1,
   BANK_NAME = :P53_BANK_NAME_1
WHERE COURT_ID = :P53_ID;
END IF;

6.
IF :P53_FINAL_AMOUNT IS NULL AND  :P53_FINAL_ORDER_DATE IS NOT NULL THEN
UPDATE TNEGA_JUDGE_LOGIN_T
SET ORDER_NO = :P53_ORDER_NO,
    COURT_FILE_DATE = :P53_COURT_FILE_DATE,
    NAME_OF_COURT = :P53_NAME_OF_COURT,
    FINAL_AMOUNT = :P53_FINAL_AMOUNT,
    FINAL_ORDER_DATE = :P53_FINAL_ORDER_DATE, 
    JUDGEMENT = :P53_JUDGEMENT,
    TYPE = :P53_TYPE,
    CHANGE_BANK_ACCOUNT = :P53_CHANGE_BANK_ACCOUNT,
    INTERIM_AWARDED_YES = :P53_INTERIM_AWARDED_YES,
    BRANCH_NAME=:P53_BRANCH_NAME_1,
    BAK_ACCOUNT=:P53_BAK_ACCOUNT,
    IFSC_CODE=:P53_IFSC_CODE_1,
    ACCOUNT_NUMBER=:P53_ACCOUNT_NUMBER_1,
   BANK_NAME = :P53_BANK_NAME_1
WHERE COURT_ID = :P53_ID;
END IF;

7.
UPDATE TNEGA_JUDGE_LOGIN_T
SET FINAL_AMOUNT = :P53_FINAL_AMOUNT,
    FINAL_ORDER_DATE = :P53_FINAL_ORDER_DATE
WHERE COURT_ID = :P53_ID 
    AND INTERIM_AMOUNT IS NOT NULL 
    AND INTERIM_ORDER_DATE IS NOT NULL;


8. 
IF :P53_INTERIM is not null then
UPDATE TNEGA_JUDGE_LOGIN_T 
SET INTERIM = :P53_INTERIM,
    INTERIM_ATTACH_FILENAME = :P53_INTERIM_ATTACH_FILENAME,
	INTERIM_ATTACH_MIMETYPE = :P53_INTERIM_ATTACH_MIMETYPE
WHERE COURT_ID = :P53_COURT_ID;
END IF;

9.
IF :P53_FINAL is not null then
UPDATE TNEGA_JUDGE_LOGIN_T
SET FINAL = :P53_FINAL,
    FINAL_ATTACH_FILENAME = :P53_FINAL_ATTACH_FILENAME,
	FINAL_ATTACH_MIMETYPE = :P53_FINAL_ATTACH_MIMETYPE
WHERE COURT_ID = :P53_COURT_ID;
end if;
		   
		   
--Disbursal Status
SELECT 
    ID,
    STATUS,
    CREATED_BY,
    CREATED_DATE,
    UPDATED_BY,
    UPDATED_DATE,
	PROCEED_INTERIM,
    PROCEED_ATTACH_MIMETYPE,
    PROCEED_ATTACH_FILENAME,
    COURT_ID,							--P53_COURT_ID_1
    SENIORITY_LEVEL,
    REMARKS,
    FIR_NO,
    COURT_FILE_NO,
	PROCEED_FINAL ,
    NEFT_ATTACH_MIMETYPE,
    NEFT_ATTACH_FILENAME,
    CHANGE_BANK_ACCOUNT,
    NEW_STATUS,
    BAK_ACCOUNT,
    BANK_NAME,
    BRANCH_NAME,
    ACCOUNT_NUMBER,
    IFSC_CODE,
    REMARKS_BANK,
    ACC_HOLDER_NAME,
    PROCEED_INTERIM,
    FINAL_PAYMENT_STATUS,
    INTERIM_PAYMENT_STATUS
FROM 
    TNEA_SUPERINTENDENT_T
	WHERE Court_id = :P1_ID;


-- #*#**#*#*#*#**#*#*#*#**#*#*#**#*#**#*#*#**#* Directorate #*#*#**#*#*#*#**#*#*#*#**#*#*#*#*#**
-- 1. Dashbord 1:
SELECT 
    ROW_NUMBER() OVER (ORDER BY O.UPDATED_DATE DESC) AS Sl_No, 
    A.*
FROM (
    SELECT 
        O.ID,
        O.DISTRICT_NAME,
        O.POL_STAT,
        O.CHILD_GENDER,
        O.Created_Date,
        O.COMPLAINT_NAME,
        O.DATE_OF_FIR,
        O.FIR_NO,
		O.COMPLAINT_COPY,
        O.COMPLAINT_COPY_MIMETYPE,
        O.COMPLAINT_COPY_FILENAME,
        O.NAME_PARENT,
        O.WILLINGNESS_COMPENSATION,
        COALESCE(O.WHO_NAME, '-') AS WHO_NAME,
        COALESCE(O.WHO_RELATIONSHIP, '-') AS WHO_RELATIONSHIP,
        COALESCE(TO_CHAR(O.WHO_DATE, 'DD-Mon-YYYY'), '-') AS WHO_DATE,
        COALESCE(O.ACCOUNT_NUMBER, '-') AS ACCOUNT_NUMBER,
        COALESCE(O.BANK_NAME, '-') AS BANK_NAME,
        COALESCE(O.BRANCH_NAME, '-') AS BRANCH_NAME,
        COALESCE(O.ACCOUNT_HOLDER_NAME, '-') AS ACCOUNT_HOLDER_NAME,
        COALESCE(O.IFSC_CODE, '-') AS IFSC_CODE,
        C.ORDER_NO,
        O.CHARGE_SHEET_YES_NO,
        COALESCE(TO_CHAR(O.CHARGE_SHEET_DATE, 'DD-Mon-YYYY'), '-') AS CHARGE_SHEET_DATE,
        C.id AS cid,
        C.INTERIM_ORDER_DATE,
        C.FINAL_AMOUNT,
        C.INTERIM_AMOUNT,
        C.TYPE,
        C.FINAL_ORDER_DATE,
        C.JUDGEMENT,
        CASE 
            WHEN O.REQUEST_STATUS = 'CO' THEN 'Paid'
            WHEN O.REQUEST_STATUS IN ('E', 'S', 'F1', 'C') THEN 'Pending'
            ELSE NULL
        END AS Payment_Status,
        CURRENT_DATE - O.CHARGE_SHEET_DATE AS DURATION,
        C.INTERIM,
        C.FINAL,
        S.PROCEED_INTERIM,
        S.PROCEED_FINAL,
        S.NEW_STATUS,
        S.INTERIM_PAYMENT_STATUS,
        S.FINAL_PAYMENT_STATUS,
        C.INTERIM,
		C.FINAL,
        S.Proceed_interim,
        S.Proceed_final,
        S.court_id,
        S.id AS sid,
        C.INTERIM_AWARDED_YES,
        O.INTERIM_YES,
        O.FINAL_YES,
        C.NAME_OF_COURT,
        CASE
            WHEN O.WILLINGNESS_COMPENSATION = 'No' THEN 'Not awarded'
            WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AWARDED_YES = 'No' THEN 'Not awarded'
            WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AWARDED_YES = 'Yes' AND S.PROCEED_INTERIM IS NULL THEN 'Pending'
            WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AWARDED_YES = 'Yes' AND S.PROCEED_INTERIM IS NOT NULL THEN 'Disbursed'
            ELSE 'Pending'
        END AS Condition_Status,
        CASE
            WHEN C.FINAL IS NOT NULL THEN 'Orders passed'
            WHEN C.FINAL IS NULL THEN 'Pending Trail'
            ELSE 'Pending'
        END AS Condition_Status_1,
        CASE
            WHEN O.WILLINGNESS_COMPENSATION = 'No' THEN 'Not awarded'
            WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND S.PROCEED_FINAL IS NULL THEN 'Pending'
            WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND S.PROCEED_FINAL IS NOT NULL THEN 'Disbursed'
            ELSE 'Pending'
        END AS Condition_Status_2,
        CURRENT_DATE - O.DATE_OF_FIR AS Aging_of_cases,
        O.CHARGE_SHEET_DATE - O.DATE_OF_FIR AS Aging_of_chargesheet_date,
        O.NAME_MEDICAL_INSTITUTION,
        O.COMPLAINT_MADE,
        O.DATE_REQUISITION_MEDICAL_EXAMINATION,
        O.DATE_OF_MEDICAL_EXAMINATION_VICTIM,
        O.DATE_OF_INTERIM
    FROM 
        TNEGA_OVERALL_T_dup O
    INNER JOIN TNEGA_JUDGE_LOGIN_T C ON O.ID = C.COURT_ID
    INNER JOIN TNEA_SUPERINTENDENT_T S ON O.ID = S.COURT_ID
    WHERE 
        O.REQUEST_STATUS IN ('E', 'S', 'F1', 'C')
        AND (O.CREATED_DATE = COALESCE(:P1_FROM_DATE1, O.CREATED_DATE))
    ORDER BY 
        O.UPDATED_DATE DESC
) A;



-- When click on Edit Icon it move to another form page.
--1. Police ntry form
select ID,
       DISTRICT_NAME,
       POL_STAT,
       YEAR_DAT,
       FIR_NO,
       STATUS,
       CREATED_BY,
BANK_DETAILS,
       CREATED_DATE,
       UPDATED_DATE,
       UPDATED_BY,
       SENT_TO,
       DATE_OF_FIR,
       CHILD_NAME,
       CHILD_AGE,
       AGE,
       NAME_PARENT,
       ACCOUNT_NUMBER,
       BANK_NAME,
       BRANCH_NAME,
       ACCOUNT_HOLDER_NAME,
       IFSC_CODE,
	   FIR_ATTACH,
       FIR_ATTACH_MIMETYPE,
       FIR_ATTACH_FILENAME,
     COMPLAINT_NAME,
      CHARGE_SHEET_YES_NO,
     CHARGE_SHEET_DATE,
     WILLINGNESS_COMPENSATION,
	 COMPLAINT_COPY,
     COMPLAINT_COPY_MIMETYPE,
     COMPLAINT_COPY_FILENAME,
     WHO_APPLYING,
     WHO_NAME,
     WHO_RELATIONSHIP,
     WHO_DATE,
     request_status,
      CHILD_GENDER,
       DATE_REQUISITION_MEDICAL_EXAMINATION,
       DATE_OF_MEDICAL_EXAMINATION_VICTIM,
       DATE_OF_INTERIM,
       NAME_MEDICAL_INSTITUTION,
       COMPLAINT_MADE
  from TNEGA_OVERALL_T_DUP
  WHERE ID = :P56_ID;
  
-- 2. Cort Form:
select ID,
       TYPE,
       COURT_FILE_DATE,
       INTERIM_ORDER_DATE,
       ORDER_NO,
       INTERIM_AWARDED_YES,
       FINAL_AMOUNT,
       INTERIM_AMOUNT,
       AMOUNT_DEPOSIT,
       AMOUNT_DEPOSIT_NAME,
       DISBURSEMENT_CONDITION,
       STATUS,
       CREATED_BY,
       CREATED_DATE,
       UPDATED_BY,
       UPDATED_DATE,
       YES_TYPE,
       REMARKS,
       COURT_ID,
       FIR_NO,
       FINAL_ORDER_DATE,
       JUDGEMENT,
       CHANGE_BANK_ACCOUNT,
       BAK_ACCOUNT,
       IFSC_CODE,
       BANK_NAME,
       BRANCH_NAME,
       ACCOUNT_NUMBER,
       REMARKS_BANK,
	   INTERIM,
       INTERIM_ATTACH_MIMETYPE,
       INTERIM_ATTACH_FILENAME,
	   FINAL,
	   FINAL_ATTACH_MIMETYPE,
	   FINAL_ATTACH_FILENAME,
	   NAME_OF_COURT
  from TNEGA_JUDGE_LOGIN_T
WHERE Court_ID =   :P56_ID;


-- 3. Disbursal Status
SELECT 
    ID,
    STATUS,
    CREATED_BY,
    CREATED_DATE,
    UPDATED_BY,
    UPDATED_DATE,
	PROCEED_INTERIM,
    PROCEED_ATTACH_MIMETYPE,
    PROCEED_ATTACH_FILENAME,
    COURT_ID,
    SENIORITY_LEVEL,
    REMARKS,
    FIR_NO,
    COURT_FILE_NO,
	PROCEED_FINAL,
    NEFT_ATTACH_MIMETYPE,
    NEFT_ATTACH_FILENAME,
    CHANGE_BANK_ACCOUNT,
    NEW_STATUS,
    BAK_ACCOUNT,
    BANK_NAME,
    BRANCH_NAME,
    ACCOUNT_NUMBER,
    IFSC_CODE,
    REMARKS_BANK,
    ACC_HOLDER_NAME,
    FINAL_PAYMENT_STATUS,
    INTERIM_PAYMENT_STATUS
FROM 
    TNEA_SUPERINTENDENT_T
	WHERE ID = :P56_ID;


1.
UPDATE TNEGA_OVERALL_T_DUP O
SET O.request_status = 'F1'
WHERE 
    O.ID = :P56_COURT_ID_1 
    AND O.ID = (SELECT J.COURT_ID FROM TNEGA_JUDGE_LOGIN_T J WHERE J.COURT_ID = :P56_COURT_ID_1 AND J.TYPE = 'Interim Compensation');


2.
UPDATE TNEGA_OVERALL_T_DUP O
SET O.request_status = 'CO'
WHERE 
    O.ID = :P56_COURT_ID_1 
    AND O.ID = (SELECT J.COURT_ID FROM TNEGA_JUDGE_LOGIN_T J WHERE J.COURT_ID = :P56_COURT_ID_1 AND J.TYPE = 'Final Compensation');

3.
update TNEA_SUPERINTENDENT_T 
set NEW_STATUS=:P56_NEW_STATUS,
INTERIM_PAYMENT_STATUS=:P56_INTERIM_PAYMENT_STATUS,
FINAL_PAYMENT_STATUS=:P56_FINAL_PAYMENT_STATUS
 WHERE court_ID=:P56_COURT_ID_1;

4.
UPDATE TNEGA_OVERALL_T_DUP
SET request_status = 'CO'
WHERE ID = :P56_COURT_ID_1
  AND EXISTS ( SELECT 1 FROM TNEGA_JUDGE_LOGIN_T
               WHERE COURT_ID = :P56_COURT_ID_1
			   AND FINAL_AMOUNT IS NOT NULL);


5.
IF :P56_INTERIM_PROCEEDINGS is not null then
UPDATE TNEA_SUPERINTENDENT_T 
SET         PROCEED_INTERIM =  :P56_PROCEED_INTERIM,
    PROCEED_ATTACH_FILENAME = :P56_FILENAME,
	PROCEED_ATTACH_MIMETYPE = :P56_MIME_TYPE
	         WHERE COURT_ID = :P56_COURT_ID_1;
END IF;


6.
IF :P56_FINAL_PROCEEDINGS is not null then
    UPDATE TNEA_SUPERINTENDENT_T 
	SET PROCEED_FINAL = :P56_PROCEED_FINAL,
		NEFT_ATTACH_FILENAME = :P56_FILENAME,	           
        NEFT_ATTACH_MIMETYPE = :P56_MIME_TYPE
		      WHERE COURT_ID = :P56_COURT_ID_1;
END IF;



------------------------------------------------------------
--2. Dashboard2:
SELECT 
    ROW_NUMBER() OVER (ORDER BY O.UPDATED_DATE DESC) AS Sl_No, 
    A.*
FROM (
    SELECT 
        O.ID,
        O.DISTRICT_NAME,
        O.POL_STAT,
        O.CHILD_GENDER,
        O.Created_Date,
        O.COMPLAINT_NAME,
        O.DATE_OF_FIR,
        O.FIR_NO,
		O.COMPLAINT_COPY,
        O.COMPLAINT_COPY_MIMETYPE,
        O.COMPLAINT_COPY_FILENAME,
        O.NAME_PARENT,
        O.WILLINGNESS_COMPENSATION,
        COALESCE(O.WHO_NAME, '-') AS WHO_NAME,
        COALESCE(O.WHO_RELATIONSHIP, '-') AS WHO_RELATIONSHIP,
        COALESCE(TO_CHAR(O.WHO_DATE, 'DD-Mon-YYYY'), '-') AS WHO_DATE,
        COALESCE(O.ACCOUNT_NUMBER, '-') AS ACCOUNT_NUMBER,
        COALESCE(O.BANK_NAME, '-') AS BANK_NAME,
        COALESCE(O.BRANCH_NAME, '-') AS BRANCH_NAME,
        COALESCE(O.ACCOUNT_HOLDER_NAME, '-') AS ACCOUNT_HOLDER_NAME,
        COALESCE(O.IFSC_CODE, '-') AS IFSC_CODE,
        C.ORDER_NO,
        O.CHARGE_SHEET_YES_NO,
        COALESCE(TO_CHAR(O.CHARGE_SHEET_DATE, 'DD-Mon-YYYY'), '-') AS CHARGE_SHEET_DATE,
        C.id AS cid,
        C.INTERIM_ORDER_DATE,
        C.FINAL_AMOUNT,
        C.INTERIM_AMOUNT,
        C.TYPE,
        C.FINAL_ORDER_DATE,
        C.JUDGEMENT,
        CASE 
            WHEN O.REQUEST_STATUS = 'CO' THEN 'Paid'
            WHEN O.REQUEST_STATUS IN ('E', 'S', 'F1', 'C') THEN 'Pending'
            ELSE NULL
        END AS Payment_Status,
        CURRENT_DATE - O.CHARGE_SHEET_DATE AS DURATION,
        S.PROCEED_INTERIM,
        S.PROCEED_FINAL,
        S.NEW_STATUS,
        S.INTERIM_PAYMENT_STATUS,
        S.FINAL_PAYMENT_STATUS,
        C.INTERIM,
        C.FINAL,
        S.PROCEED_INTERIM,
        S.PROCEED_FINAL,
        S.court_id,
        S.id AS sid,
        C.INTERIM_AWARDED_YES,
        O.INTERIM_YES,
        O.FINAL_YES,
        C.NAME_OF_COURT,
        CASE
            WHEN O.WILLINGNESS_COMPENSATION = 'No' THEN 'Not awarded'
            WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AWARDED_YES = 'No' THEN 'Not awarded'
            WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AWARDED_YES = 'Yes' AND S.PROCEED_INTERIM IS NULL THEN 'Pending'
            WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AWARDED_YES = 'Yes' AND S.PROCEED_INTERIM IS NOT NULL THEN 'Disbursed'
            ELSE 'Pending'
        END AS Condition_Status,
        CASE
            WHEN C.FINAL IS NOT NULL THEN 'Orders passed'
            WHEN C.FINAL IS NULL THEN 'Pending Trail'
            ELSE 'Pending'
        END AS Condition_Status_1,
        CASE
            WHEN O.WILLINGNESS_COMPENSATION = 'No' THEN 'Not awarded'
            WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND S.PROCEED_FINAL IS NULL THEN 'Pending'
            WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND S.PROCEED_FINAL IS NOT NULL THEN 'Disbursed'
            ELSE 'Pending'
        END AS Condition_Status_2,
        CURRENT_DATE - O.DATE_OF_FIR AS Aging_of_cases,
        O.CHARGE_SHEET_DATE - O.DATE_OF_FIR AS Aging_of_chargesheet_date,
        O.NAME_MEDICAL_INSTITUTION,
        O.COMPLAINT_MADE,
        O.DATE_REQUISITION_MEDICAL_EXAMINATION,
        O.DATE_OF_MEDICAL_EXAMINATION_VICTIM,
        O.DATE_OF_INTERIM
    FROM 
        TNEGA_OVERALL_T_dup O
    INNER JOIN TNEGA_JUDGE_LOGIN_T C ON O.ID = C.COURT_ID
    INNER JOIN TNEA_SUPERINTENDENT_T S ON O.ID = S.COURT_ID
    WHERE 
        O.REQUEST_STATUS IN ('E', 'S', 'F1', 'C')
        AND (O.CREATED_DATE = COALESCE(:P1_FROM_DATE1, O.CREATED_DATE))
    ORDER BY 
        O.UPDATED_DATE DESC
) A;

SELECT 
    ROW_NUMBER() OVER () AS Sl_No, 
    A.*
FROM (
    SELECT 
        O.ID,
        O.DISTRICT_NAME,
        O.POL_STAT,
        O.CHILD_GENDER,
        O.Created_Date,
        O.COMPLAINT_NAME,
        O.DATE_OF_FIR,
        O.FIR_NO,
		O.COMPLAINT_COPY,
        O.COMPLAINT_COPY_MIMETYPE,
        O.COMPLAINT_COPY_FILENAME,
        O.NAME_PARENT,
        O.WILLINGNESS_COMPENSATION,
        COALESCE(O.WHO_NAME, '-') AS WHO_NAME,
        COALESCE(O.WHO_RELATIONSHIP, '-') AS WHO_RELATIONSHIP,
        COALESCE(TO_CHAR(O.WHO_DATE, 'DD-Mon-YYYY'), '-') AS WHO_DATE,
        COALESCE(O.ACCOUNT_NUMBER, '-') AS ACCOUNT_NUMBER,
        COALESCE(O.BANK_NAME, '-') AS BANK_NAME,
        COALESCE(O.BRANCH_NAME, '-') AS BRANCH_NAME,
        COALESCE(O.ACCOUNT_HOLDER_NAME, '-') AS ACCOUNT_HOLDER_NAME,
        COALESCE(O.IFSC_CODE, '-') AS IFSC_CODE,
        C.ORDER_NO,
        O.CHARGE_SHEET_YES_NO,
        COALESCE(TO_CHAR(O.CHARGE_SHEET_DATE, 'DD-Mon-YYYY'), '-') AS CHARGE_SHEET_DATE,
        C.id AS cid,
        C.INTERIM_ORDER_DATE,
        C.FINAL_AMOUNT,
        C.INTERIM_AMOUNT,
        C.TYPE,
        C.FINAL_ORDER_DATE,
        C.JUDGEMENT,
        CASE 
            WHEN O.REQUEST_STATUS = 'CO' THEN 'Paid'
            WHEN O.REQUEST_STATUS IN ('E', 'S', 'F1', 'C') THEN 'Pending'
            ELSE NULL
        END AS Payment_Status,
        CURRENT_DATE - O.CHARGE_SHEET_DATE AS DURATION,
        S.PROCEED_INTERIM,
        S.PROCEED_FINAL,
        S.NEW_STATUS,
        S.INTERIM_PAYMENT_STATUS,
        S.FINAL_PAYMENT_STATUS,
        C.INTERIM,
        C.FINAL,
        S.PROCEED_INTERIM,
        S.PROCEED_FINAL,
        S.court_id,
        S.id AS sid,
        C.INTERIM_AWARDED_YES,
        O.INTERIM_YES,
        O.FINAL_YES,
        C.NAME_OF_COURT,
        CASE
            WHEN O.WILLINGNESS_COMPENSATION = 'No' THEN 'Not awarded'
            WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AWARDED_YES = 'No' THEN 'Not awarded'
            WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AWARDED_YES = 'Yes' AND S.PROCEED_INTERIM IS NULL THEN 'Pending'
            WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AWARDED_YES = 'Yes' AND S.PROCEED_INTERIM IS NOT NULL THEN 'Disbursed'
            ELSE 'Pending'
        END AS Condition_Status,
        CASE
            WHEN C.FINAL IS NOT NULL THEN 'Orders passed'
            WHEN C.FINAL IS NULL THEN 'Pending Trail'
            ELSE 'Pending'
        END AS Condition_Status_1,
        CASE
            WHEN O.WILLINGNESS_COMPENSATION = 'No' THEN 'Not awarded'
            WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND S.PROCEED_FINAL IS NULL THEN 'Pending'
            WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND S.PROCEED_FINAL IS NOT NULL THEN 'Disbursed'
            ELSE 'Pending'
        END AS Condition_Status_2,
        CURRENT_DATE - O.DATE_OF_FIR AS Aging_of_cases,
        O.CHARGE_SHEET_DATE - O.DATE_OF_FIR AS Aging_of_chargesheet_date,
        O.NAME_MEDICAL_INSTITUTION,
        O.COMPLAINT_MADE,
        O.DATE_REQUISITION_MEDICAL_EXAMINATION,
        O.DATE_OF_MEDICAL_EXAMINATION_VICTIM,
        O.DATE_OF_INTERIM
    FROM 
        TNEGA_OVERALL_T_dup O
    INNER JOIN TNEGA_JUDGE_LOGIN_T C ON O.ID = C.COURT_ID
    INNER JOIN TNEA_SUPERINTENDENT_T S ON O.ID = S.COURT_ID
    WHERE 
        O.REQUEST_STATUS IN ('E', 'S', 'F1', 'C')
    --    AND (O.CREATED_DATE = COALESCE(:P1_FROM_DATE1, O.CREATED_DATE))
    ORDER BY 
        O.UPDATED_DATE DESC
) A

-- When click on Edit it move to another form page:
--1. Police
select
ID, DISTRICT_NAME,
       POL_STAT,
       YEAR_DAT,
       FIR_NO,
       STATUS,
       CREATED_BY,
       CREATED_DATE,
       UPDATED_DATE,
       UPDATED_BY,
       SENT_TO,
       DATE_OF_FIR,
       CHILD_NAME,
       CHILD_AGE,
       AGE,
       NAME_PARENT,
       ACCOUNT_NUMBER,
       BANK_NAME,
       BRANCH_NAME,
       ACCOUNT_HOLDER_NAME,
       IFSC_CODE,
	   FIR_ATTACH,
       FIR_ATTACH_MIMETYPE,
       FIR_ATTACH_FILENAME,
       COURT_FILE_NO,
       TYPE_OF_ORDER,
       INTERIM_DATE,
       FINAL_DATE,
       AMOUNT_OF_COMPENSATION,
	   COURT_ATTACH,
       COURT_ATTACH_MIMETYPE,
       COURT_ATTACH_FILENAME,
       COMPLAINT_NAME,
       REQUEST_STATUS,
       CHARGE_SHEET_YES_NO,
       CHARGE_SHEET_DATE,
       WILLINGNESS_COMPENSATION,
       INTERIM_YES,
       FINAL_YES,
	   COMPLAINT_COPY,
       COMPLAINT_COPY_MIMETYPE,
       COMPLAINT_COPY_FILENAME,
       WHO_APPLYING,
       WHO_NAME,
       WHO_RELATIONSHIP,
       WHO_DATE,
       BANK_DETAILS,
       ID,
       CHILD_GENDER,
       DATE_REQUISITION_MEDICAL_EXAMINATION,
       DATE_OF_MEDICAL_EXAMINATION_VICTIM,
       DATE_OF_INTERIM,
       NAME_MEDICAL_INSTITUTION,
       COMPLAINT_MADE
  from TNEGA_OVERALL_T_DUP
  WHERE ID = :P86_id;
  


-- 2. Court:
select ID,
       TYPE,
COURT_FILE_DATE,
       INTERIM_ORDER_DATE,
       ORDER_NO,
       STATUS,
       CREATED_BY,
       CREATED_DATE,
       UPDATED_BY,
       UPDATED_DATE,
       YES_TYPE,
       REMARKS,
       COURT_ID,
       FIR_NO,
       FINAL_ORDER_DATE,
       JUDGEMENT,
       CHANGE_BANK_ACCOUNT,
       BAK_ACCOUNT,
       IFSC_CODE,
       BANK_NAME,
       BRANCH_NAME,
       ACCOUNT_NUMBER,
       REMARKS_BANK,
       INTERIM_AMOUNT,
       final_amount,
	   INTERIM,
	   INTERIM_ATTACH_MIMETYPE,
       INTERIM_ATTACH_FILENAME,
	   FINAL,
	   FINAL_ATTACH_MIMETYPE,
       FINAL_ATTACH_FILENAME,
       NAME_OF_COURT,
       INTERIM_AWARDED_YES
  from TNEGA_JUDGE_LOGIN_T
  WHERE ID = :P86_COURT_ID;
  
--3. Disbursal Status
select ID,
       STATUS,
       CREATED_BY,
       CREATED_DATE,
       UPDATED_BY,
       UPDATED_DATE,
	   PROCEED_INTERIM,
       PROCEED_ATTACH_MIMETYPE,
       PROCEED_ATTACH_FILENAME,
       COURT_ID,
       SENIORITY_LEVEL,
       REMARKS,
       FIR_NO,
       COURT_FILE_NO,
	   PROCEED_FINAL,
       NEFT_ATTACH_MIMETYPE,
       NEFT_ATTACH_FILENAME,
       CHANGE_BANK_ACCOUNT,
       NEW_STATUS,
       BAK_ACCOUNT,
       BANK_NAME,
       BRANCH_NAME,
       ACCOUNT_NUMBER,
       IFSC_CODE,
       REMARKS_BANK,
       ACC_HOLDER_NAME,
       FINAL_PAYMENT_STATUS,
       INTERIM_PAYMENT_STATUS
  from TNEA_SUPERINTENDENT_T  
  WHERE ID  :P86_ID;
  



--1.   (Button: Submit1)
UPDATE TNEGA_OVERALL_T_DUP
SET   CHARGE_SHEET_YES_NO = :P86_CHARGE_SHEET_YES_NO,
      CHARGE_SHEET_DATE = :P86_CHARGE_SHEET_DATE,
      DATE_OF_MEDICAL_EXAMINATION_VICTIM = :P86_DATE_OF_MEDICAL_EXAMINATION_VICTIM
WHERE ID = :P86_ID;


--2.  (Button: Submit2)
UPDATE TNEGA_JUDGE_LOGIN_T
SET ORDER_NO = :P86_ORDER_NO,
    COURT_FILE_DATE = :P86_COURT_FILE_DATE,
	NAME_OF_COURT = :P86_NAME_OF_COURT,
	TYPE = :P86_TYPE,
	INTERIM_ORDER_DATE = :P86_INTERIM_ORDER_DATE,
	INTERIM_AMOUNT = :P86_INTERIM_AMOUNT,
	INTERIM = :P86_INTERIM,
	INTERIM_ATTACH_FILENAME = :P86_INTERIM_ATTACH_FILENAME,
	INTERIM_ATTACH_MIMETYPE = :P86_INTERIM_ATTACH_MIMETYPE,
	FINAL_ORDER_DATE = :p86_FINAL_ORDER_DATE,
	final_amount = :P86_final_amount,
	FINAL = :P86_FINAL,
	FINAL_ATTACH_FILENAME= :P86_FINAL_ATTACH_FILENAME,
	FINAL_ATTACH_MIMETYPE = :P86_FINAL_ATTACH_MIMETYPE,       ,
	JUDGEMENT = :P86_JUDGEMENT,
	INTERIM_AWARDED_YES = :P86_INTERIM_AWARDED_YES,
	CHANGE_BANK_ACCOUNT = :p86_CHANGE_BANK_ACCOUNT,
	ACCOUNT_NUMBER = :P86_ACCOUNT_NUMBER,
	BAK_ACCOUNT = :P86_BAK_ACCOUNT,
	BANK_NAME = :P86_BANK_NAME,
	BRANCH_NAME = :P86_BRANCH_NAME,
	IFSC_CODE = :P86_IFSC_CODE  
  WHERE ID = :P86_COURT_ID;    
	
    
-- 3. (Button: Submit3)
UPDATE TNEA_SUPERINTENDENT_T
SET NEW_STATUS = :P86_NEW_STATUS,
    INTERIM_PAYMENT_STATUS = :P86_INTERIM_PAYMENT_STATUS,
	PROCEED_INTERIM = :P86_PROCEED_INTERIM,
	PROCEED_ATTACH_FILENAME = :p86_PROCEED_ATTACH_FILENAME,
	PROCEED_ATTACH_MIMETYPE = :P86_PROCEED_ATTACH_MIMETYPE,
	FINAL_PAYMENT_STATUS = :P86_FINAL_PAYMENT_STATUS,
	PROCEED_FINAL       = :P86_PROCEED_FINAL,
	NEFT_ATTACH_FILENAME = :P86_NEFT_ATTACH_FILENAME,
	NEFT_ATTACH_MIMETYPE =:P86_NEFT_ATTACH_MIMETYPE
WHERE ID = :P86_ID;
  

    




--4. (Button: Submit2)
update TNEGA_OVERALL_T_DUP 
set IFSC_CODE=COALESCE(:P86_IFSC_CODE_1, :P86_IFSC_CODE),
    BANK_NAME= COALESCE(:P86_BANK_NAME_1, :P86_BANK_NAME), 
	BRANCH_NAME= COALESCE(:P86_BRANCH_NAME_1, :P86_BRANCH_NAME),
	ACCOUNT_NUMBER= COALESCE(:P86_ACCOUNT_NUMBER_1, :P86_ACCOUNT_NUMBER),
	ACCOUNT_HOLDER_NAME= COALESCE(:P86_BAK_ACCOUNT, :P86_ACCOUNT_HOLDER_NAME )
where id=:P86_COURT_ID;


--5.  (Button: Submit2)
UPDATE TNEGA_OVERALL_T_DUP O 
SET O.request_status = 'S'
WHERE O.id = :P86_COURT_ID ;


--6.  (Button: Submit2)
UPDATE TNEGA_OVERALL_T_DUP O
SET O.request_status = 'C'
WHERE O.ID = :P86_COURT_ID_1 
AND O.ID = (SELECT J.COURT_ID FROM TNEA_SUPERINTENDENT_T J 
            WHERE J.COURT_ID = :P86_ID 
			AND J.NEW_STATUS = 'Interim Order Status');

--7. (Button: Submit2)
IF :P86_INTERIM_AMOUNT IS NOT NULL AND  :P86_INTERIM_ORDER_DATE IS NOT NULL THEN
UPDATE TNEGA_JUDGE_LOGIN_T
SET ORDER_NO = :P86_ORDER_NO,
    COURT_FILE_DATE = :P86_COURT_FILE_DATE,
    NAME_OF_COURT = :P86_NAME_OF_COURT,
    INTERIM_ORDER_DATE = :P86_INTERIM_ORDER_DATE,
    INTERIM_AMOUNT = :P86_INTERIM_AMOUNT,
    JUDGEMENT = :P86_JUDGEMENT,
    TYPE = :P86_TYPE,
    CHANGE_BANK_ACCOUNT = :P86_CHANGE_BANK_ACCOUNT,
    INTERIM_AWARDED_YES = :P86_INTERIM_AWARDED_YES,
    BRANCH_NAME=:P86_BRANCH_NAME_1,
    BAK_ACCOUNT=:P86_BAK_ACCOUNT,
    IFSC_CODE=:P86_IFSC_CODE_1,
    ACCOUNT_NUMBER=:P86_ACCOUNT_NUMBER_1,
   BANK_NAME = :P86_BANK_NAME_1
WHERE COURT_ID = :P86_ID;
END IF;


IF :P86_INTERIM_AMOUNT IS NULL AND  :P86_INTERIM_ORDER_DATE IS NULL THEN

UPDATE TNEGA_JUDGE_LOGIN_T
SET ORDER_NO = :P86_ORDER_NO,
    COURT_FILE_DATE = :P86_COURT_FILE_DATE,
    NAME_OF_COURT = :P86_NAME_OF_COURT,
    FINAL_AMOUNT = :P86_FINAL_AMOUNT,
    FINAL_ORDER_DATE = :P86_FINAL_ORDER_DATE, 
    JUDGEMENT = :P86_JUDGEMENT,
    TYPE = :P86_TYPE,
    CHANGE_BANK_ACCOUNT = :P86_CHANGE_BANK_ACCOUNT,
    INTERIM_AWARDED_YES = :P86_INTERIM_AWARDED_YES,
    BRANCH_NAME=:P86_BRANCH_NAME_1,
    BAK_ACCOUNT=:P86_BAK_ACCOUNT,
    IFSC_CODE=:P86_IFSC_CODE_1,
    ACCOUNT_NUMBER=:P86_ACCOUNT_NUMBER_1,
   BANK_NAME = :P86_BANK_NAME_1
WHERE COURT_ID = :P86_ID;

END IF;

--8.  (Button: Submit2)
UPDATE TNEGA_JUDGE_LOGIN_T
SET FINAL_AMOUNT = :P86_FINAL_AMOUNT,
    FINAL_ORDER_DATE = :P86_FINAL_ORDER_DATE
WHERE COURT_ID = :P86_ID 
AND INTERIM_AMOUNT IS NOT NULL 
AND INTERIM_ORDER_DATE IS NOT NULL;

--9.  (Button: Submit2)
IF :P86_INTERIM is not null then
    UPDATE TNEGA_JUDGE_LOGIN_T 
	SET INTERIM = :P86_INTERIM,
	    INTERIM_ATTACH_FILENAME = :P86_INTERIM_ATTACH_FILENAME,
      	INTERIM_ATTACH_MIMETYPE = :P86_INTERIM_ATTACH_MIMETYPE
                WHERE COURT_ID = :P86_COURT_ID;
   

--10.  (Button: Submit2)
IF :P86_FINAL is not null then
UPDATE TNEGA_JUDGE_LOGIN_T 
    SET FINAL = :P86_FINAL,
	    FINAL_ATTACH_FILENAME = :P86_FINAL_ATTACH_FILENAME,
		FINAL_ATTACH_MIMETYPE = :P86_FINAL_ATTACH_MIMETYPE
               WHERE COURT_ID = :P86_COURT_ID;
      

-- 11. (Button: Submit3)
UPDATE TNEGA_OVERALL_T_DUP O
SET O.request_status = 'F1'
WHERE O.ID = :P86_COURT_ID_1 
AND O.ID = (SELECT J.COURT_ID FROM TNEGA_JUDGE_LOGIN_T J 
            WHERE J.COURT_ID = :P86_COURT_ID_1 
			AND J.TYPE = 'Interim Compensation');

UPDATE TNEGA_OVERALL_T_DUP O
SET O.request_status = 'CO'
WHERE O.ID = :P86_COURT_ID_1 
AND O.ID = (SELECT J.COURT_ID FROM TNEGA_JUDGE_LOGIN_T J 
            WHERE J.COURT_ID = :P86_COURT_ID_1 
			AND J.TYPE = 'Final Compensation');


--12.  (Button: Submit3)
update TNEA_SUPERINTENDENT_T 
set NEW_STATUS=:P86_NEW_STATUS,
    INTERIM_PAYMENT_STATUS=:P86_INTERIM_PAYMENT_STATUS,
	FINAL_PAYMENT_STATUS=:P86_FINAL_PAYMENT_STATUS
 WHERE court_ID=:P86_COURT_ID_1;

--13.  (Button: Submit3)
UPDATE TNEGA_OVERALL_T_DUP
SET request_status = 'CO'
WHERE ID = :P86_COURT_ID_1
  AND EXISTS (SELECT 1 FROM TNEGA_JUDGE_LOGIN_T
              WHERE COURT_ID = :P86_COURT_ID_1
			  AND FINAL_AMOUNT IS NOT NULL);

--14.  (Button: Submit3)
IF :P86_INTERIM_PROCEEDINGS is not null then
    UPDATE TNEA_SUPERINTENDENT_T 
    SET PROCEED_INTERIM = :P86_PROCEED_INTERIM,
	     PROCEED_ATTACH_FILENAME = :P86_PROCEED_ATTACH_FILENAME,
         PROCEED_ATTACH_MIMETYPE = :P86_PROCEED_ATTACH_MIMETYPE
                WHERE COURT_ID = :P86_COURT_ID_1;

--15.  (Button: Submit3)
IF :P86_FINAL_PROCEEDINGS is not null then
    UPDATE TNEA_SUPERINTENDENT_T 
    SET PROCEED_FINAL = :P86_PROCEED_FINAL,
	    NEFT_ATTACH_FILENAME = :P86_NEFT_ATTACH_FILENAME,
		NEFT_ATTACH_MIMETYPE = :P86_NEFT_ATTACH_MIMETYPE
	WHERE COURT_ID = :P86_COURT_ID_1;




-- #*#*#**#*#*#*#*#**#*#*#*#*#*#**#*#*#*#*#**#*# District Admin:#*#*#**#*#*#*#*#*#*#*#**#*#*#*#*#*#*#*#*
Sivagangai
Col_Sivagangai$123
--1. Dashboard:	
SELECT 
    ROW_NUMBER() OVER (ORDER BY 1 ASC) AS ROWNUM,
    A.*, 
    ROUND(
        COALESCE(
            (A."No_of_cases_Convicted" / NULLIF(A."Final_Compensation_No_of_cases_awarded", 0) * 100),
            0
        ), 
        2
    ) AS "Conviction_rate",
    (COALESCE(A."Interim_Compensation_Pending_Amount", 0) + COALESCE(A."Final_Compensation_Pending_Amount", 0)) AS TOTAL
FROM (
    SELECT DISTINCT
        OT.DISTRICT_NAME,
        OT.POL_STAT,
        (SELECT COUNT(*) FROM TNEGA_OVERALL_T_DUP O WHERE O.DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT AND WILLINGNESS_COMPENSATION = 'Yes' ) AS WILLINGNESS_COMPENSATION,
        (SELECT COUNT(*) FROM TNEGA_OVERALL_T_DUP O WHERE O.DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT ) AS "No_of_POCSO_cases_filed",
        (SELECT COUNT(*) FROM TNEGA_OVERALL_T_DUP O WHERE O.REQUEST_STATUS IN ('E', 'S', 'F1') AND O.DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT ) AS "Case_Status_Pending",
        (SELECT COUNT(*) FROM TNEGA_OVERALL_T_DUP O WHERE O.REQUEST_STATUS IN ('CO', 'C') AND O.DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Case_Status_Completed",
        COALESCE((SELECT COUNT(*) FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O WHERE J.JUDGEMENT = 'Acquittal' AND O.ID = J.COURT_ID AND O.POL_STAT = OT.POL_STAT AND DISTRICT_NAME = OT.DISTRICT_NAME GROUP BY DISTRICT_NAME), 0) AS "No_of_cases_Acquitted",
        COALESCE((SELECT COUNT(*) FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O WHERE TRIM(J.JUDGEMENT) = 'Convicted' AND O.ID = J.COURT_ID AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT), 0) AS "No_of_cases_Convicted",
        (SELECT COUNT(*) FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O WHERE TRIM(J.JUDGEMENT) = 'Others' AND O.ID = J.COURT_ID AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT ) AS "Other_Disposals",
        (SELECT COUNT(*) FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O WHERE j.INTERIM_AMOUNT IS NOT NULL AND o.ID = j.court_id AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT ) AS "Interim_Compensation_No_of_cases_awarded",
        (SELECT COALESCE(SUM(j.INTERIM_AMOUNT), 0) FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O WHERE j.INTERIM_AMOUNT IS NOT NULL AND o.ID = j.court_id AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT ) AS "Interim_Compensation_awarded_Amount",
        (SELECT COUNT(*) FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O WHERE j.INTERIM_AMOUNT IS NOT NULL AND o.ID = j.court_id AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT ) AS "Interim_Compensation_No_of_cases_Disbursed",
        (SELECT COALESCE(SUM(j.INTERIM_AMOUNT), 0) FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O WHERE j.INTERIM_AMOUNT IS NOT NULL AND o.ID = j.court_id AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Interim_Compensation_Disbursed_Amount",
        (SELECT COUNT(*) FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O WHERE J.TYPE = 'Interim Compensation' AND O.REQUEST_STATUS IN ('E', 'S', 'F1') AND O.ID = j.court_id AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT ) AS "Interim_Compensation_No_of_cases_Pending",
        (SELECT COALESCE(SUM(j.INTERIM_AMOUNT), 0) FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O WHERE J.TYPE = 'Interim Compensation' AND O.REQUEST_STATUS IN ('E', 'S', 'F1') AND O.ID = j.court_id AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT ) AS "Interim_Compensation_Pending_Amount",
        (SELECT COUNT(*) FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O WHERE J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('CO','C') AND O.ID = j.court_id AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT ) AS "Final_Compensation_No_of_cases_Disbursed",
        (SELECT COALESCE(SUM(j.FINAL_AMOUNT), 0) FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O WHERE J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('CO','C') AND O.ID = j.court_id AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT ) AS "Final_Compensation_Disbursed_Amount",
        (SELECT COUNT(*) FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O WHERE J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('C','CO') AND O.ID = j.court_id AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Final_Compensation_No_of_cases_awarded",
        (SELECT COALESCE(SUM(j.FINAL_AMOUNT), 0) FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O WHERE J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('C','CO') AND O.ID = j.court_id AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT ) AS "Final_Compensation_awarded_Amount",
        (SELECT COUNT(*) FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O WHERE J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('E', 'S', 'F1', 'C') AND O.ID = j.court_id AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT ) AS "Final_Compensation_No_of_cases_Pending",
        (SELECT COALESCE(SUM(j.FINAL_AMOUNT), 0) FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O WHERE J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('E', 'S', 'F1') AND O.ID = j.court_id AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Final_Compensation_Pending_Amount",
        (SELECT COUNT(*) FROM TNEGA_OVERALL_T_DUP WHERE CHARGE_SHEET_YES_NO IN ('Yes') AND DISTRICT_NAME = OT.DISTRICT_NAME AND POL_STAT = OT.POL_STAT) AS "No_of_Chargesheet_filed"
    FROM 
        TNEGA_OVERALL_T_DUP OT
    ORDER BY 1 ASC
) A
INNER JOIN SIGNUP_T S ON A.DISTRICT_NAME = S.NAME
WHERE 
    S.ID = :APP_EMPLOYEE_ID;


SELECT * FROM public.signup_t;

-- When Click on Police station name it move to form page:
SELECT 
    OT.ID,
    OT.POL_STAT,
    OT.FIR_NO,
    OT.DATE_OF_FIR,
    (CASE 
        WHEN TJLT.COURT_FILE_DATE IS NOT NULL THEN 'Yes'
        ELSE 'No'
    END) AS "Chargesheet filled Status",
    TJLT.ORDER_NO,
    TJLT.COURT_FILE_DATE,
    CASE REQUEST_STATUS
        WHEN 'E' THEN 'Pending'
        WHEN 'S' THEN 'Pending'
        WHEN 'F1' THEN 'Pending'
        WHEN 'C' THEN 'Pending'
        WHEN 'CO' THEN 'Disposed'
    END AS STATUS,
    TJLT.JUDGEMENT,
    TJLT.INTERIM_AMOUNT,
    CASE REQUEST_STATUS
        WHEN 'E' THEN 'Pending'
        WHEN 'S' THEN 'Pending'
        WHEN 'F1' THEN 'Pending'
        WHEN 'C' THEN 'Pending'
        WHEN 'CO' THEN 'Completed'
    END AS INTERIM_STATUS,
    TJLT.FINAL_AMOUNT,
    CASE REQUEST_STATUS
        WHEN 'E' THEN 'Pending'
        WHEN 'S' THEN 'Pending'
        WHEN 'F1' THEN 'Pending'
        WHEN 'C' THEN 'Pending'
        WHEN 'CO' THEN 'Completed'
    END AS FINAL_STATUS,
    CURRENT_DATE - OT.DATE_OF_FIR AS "Aging_of_cases",
    OT.CHARGE_SHEET_DATE - OT.DATE_OF_FIR AS "Aging_of_chargesheet_date"
FROM 
    TNEGA_OVERALL_T_DUP OT
INNER JOIN 
    TNEGA_JUDGE_LOGIN_T TJLT 
    ON TJLT.COURT_ID = OT.ID 
WHERE 
    OT.POL_STAT = :P83_POLICE;




-- Customize report:
SELECT DISTINCT
    O.ID,
    O.DISTRICT_NAME,
    O.POL_STAT,
    O.CHILD_GENDER,
    O.NAME_MEDICAL_INSTITUTION,
    O.COMPLAINT_MADE,
    O.DATE_REQUISITION_MEDICAL_EXAMINATION,
    O.DATE_OF_MEDICAL_EXAMINATION_VICTIM,
    O.DATE_OF_INTERIM,
    O.COMPLAINT_NAME,
    O.DATE_OF_FIR,
    O.FIR_NO,
    C.COURT_FILE_DATE,
    C.INTERIM_AWARDED_YES,
    O.COMPLAINT_COPY_MIMETYPE,
    O.COMPLAINT_COPY_FILENAME,
    O.NAME_PARENT,
    O.WILLINGNESS_COMPENSATION,
    COALESCE(O.WHO_NAME, '-') AS WHO_NAME,
    COALESCE(O.WHO_RELATIONSHIP, '-') AS WHO_RELATIONSHIP,
    COALESCE(TO_CHAR(O.WHO_DATE, 'DD-Mon-YYYY'), '-') AS WHO_DATE,
    COALESCE(O.ACCOUNT_NUMBER, '-') AS ACCOUNT_NUMBER,
    COALESCE(O.BANK_NAME, '-') AS BANK_NAME,
    COALESCE(O.BRANCH_NAME, '-') AS BRANCH_NAME,
    COALESCE(O.ACCOUNT_HOLDER_NAME, '-') AS ACCOUNT_HOLDER_NAME,
    COALESCE(O.IFSC_CODE, '-') AS IFSC_CODE,
    C.ORDER_NO,
    O.CHARGE_SHEET_YES_NO,
    COALESCE(TO_CHAR(O.CHARGE_SHEET_DATE, 'DD-Mon-YYYY'), '-') AS CHARGE_SHEET_DATE,
    C.INTERIM_ORDER_DATE,
    C.FINAL_AMOUNT,
    C.INTERIM_AMOUNT,
    C.FINAL_ORDER_DATE,
    C.JUDGEMENT,
    CASE 
        WHEN O.REQUEST_STATUS = 'CO' THEN 'Disposed'
        WHEN O.REQUEST_STATUS IN ('E', 'S', 'F1') THEN 'Pending'
        WHEN O.REQUEST_STATUS = 'C' THEN 'Disposed'
    END AS Payment_Status,
    CURRENT_DATE - O.CHARGE_SHEET_DATE AS DURATION,
    C.NAME_OF_COURT,
    O.INTERIM_YES,
    O.FINAL_YES,
    C.INTERIM,
    C.FINAL,
    CASE
        WHEN O.WILLINGNESS_COMPENSATION = 'No' THEN 'Not awarded'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AMOUNT IS NOT NULL AND S.PROCEED_INTERIM IS NULL THEN 'Pending'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AMOUNT IS NOT NULL AND S.PROCEED_INTERIM IS NOT NULL THEN 'Disbursed'
        ELSE 'Other Condition'
    END AS Condition_Status,
    CASE
        WHEN C.FINAL_REF IS NOT NULL THEN 'Orders passed'
        WHEN C.FINAL_REF IS NULL THEN 'Pending Trail'
        ELSE 'Other Condition'
    END AS Condition_Status_1,
    CASE
        WHEN O.WILLINGNESS_COMPENSATION = 'No' THEN 'Not awarded'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND S.PROCEED_FINAL IS NULL THEN 'Pending'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND S.PROCEED_FINAL IS NOT NULL THEN 'Disbursed'
        ELSE 'Other Condition'
    END AS Condition_Status_2,
    CURRENT_DATE - O.DATE_OF_FIR AS "Aging_of_cases",
    O.CHARGE_SHEET_DATE - O.DATE_OF_FIR AS "Aging_of_chargesheet_date"
FROM 
    TNEGA_OVERALL_T_DUP O
JOIN 
    TNEGA_JUDGE_LOGIN_T C ON O.ID = C.COURT_ID
JOIN 
    TNEA_SUPERINTENDENT_T S ON O.ID = S.COURT_ID 
JOIN 
    SIGNUP_T a ON a.mobile_number = O.district_name 
WHERE 
    O.REQUEST_STATUS IN ('C','CO','E','S','F1') 
    AND a.role IN ('Admin') 
    AND a.district_name IN ('District') 
    AND a.ID = :APP_EMPLOYEE_ID
    AND (O.COMPLAINT_NAME BETWEEN COALESCE(:P80_NEW_4, O.COMPLAINT_NAME) AND COALESCE(:P80_NEW_5, O.COMPLAINT_NAME) OR :P80_NEW_4 IS NULL OR :P80_NEW_5 IS NULL)
 

-- #*#*#**#*#*#*#*#**#*#*#*#*#*#**#*#*#*#*#**#*# State Admin Login #*#*#**#*#*#*#*#*#*#*#**#*#*#*#*#*#*#*#*
Tnega
Tnega_$123
--1. Dashboard:
SELECT 
    ROW_NUMBER() OVER (ORDER BY A.DISTRICT_NAME) AS ROWNUM, 
    A.*, 
    ROUND(
        COALESCE(
            (A.No_of_cases_Convicted / NULLIF(A.Final_Compensation_No_of_cases_awarded, 0) * 100), 
            0
        ), 
        2
    ) AS Conviction_rate,
    (COALESCE(A.Interim_Compensation_Pending_Amount, 0) + COALESCE(A.Final_Compensation_Pending_Amount, 0)) AS TOTAL
FROM (
    SELECT  
        O.DISTRICT_NAME,
        COUNT(CASE WHEN O.WILLINGNESS_COMPENSATION = 'Yes' THEN 1 END) AS WILLINGNESS_COMPENSATION, 
        COUNT(*) AS No_of_POCSO_cases_filed,
        COUNT(CASE WHEN O.REQUEST_STATUS IN ('E', 'S', 'F1') THEN 1 END) AS Case_Status_Pending,
        COUNT(CASE WHEN O.REQUEST_STATUS IN ('CO', 'C') THEN 1 END) AS Case_Status_Completed,
        COALESCE(COUNT(CASE WHEN J.JUDGEMENT = 'Acquittal' THEN 1 END), 0) AS No_of_cases_Acquitted,
        COALESCE(COUNT(CASE WHEN J.JUDGEMENT = 'Convicted' THEN 1 END), 0) AS No_of_cases_Convicted,
        COUNT(CASE WHEN J.JUDGEMENT = 'Others' THEN 1 END) AS Other_Disposals,
        COUNT(CASE WHEN J.INTERIM_AMOUNT IS NOT NULL THEN 1 END) AS Interim_Compensation_No_of_cases_awarded,
        COALESCE(SUM(J.INTERIM_AMOUNT), 0) AS Interim_Compensation_awarded_Amount,
        COUNT(CASE WHEN J.INTERIM_AMOUNT IS NOT NULL THEN 1 END) AS Interim_Compensation_No_of_cases_Disbursed,
        COALESCE(SUM(CASE WHEN J.INTERIM_AMOUNT IS NOT NULL THEN COALESCE(J.INTERIM_AMOUNT, 0) END), 0) AS Interim_Compensation_Disbursed_Amount,
        COUNT(CASE WHEN J.TYPE = 'Interim Compensation' AND O.REQUEST_STATUS IN ('E', 'S', 'F1') THEN 1 END) AS Interim_Compensation_No_of_cases_Pending,
        COALESCE(SUM(CASE WHEN J.TYPE = 'Interim Compensation' AND O.REQUEST_STATUS IN ('E', 'S', 'F1') THEN COALESCE(J.INTERIM_AMOUNT, 0) END), 0) AS Interim_Compensation_Pending_Amount,
        COUNT(CASE WHEN J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('CO', 'C') THEN 1 END) AS Final_Compensation_No_of_cases_Disbursed,
        COALESCE(SUM(CASE WHEN J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('CO', 'C') THEN COALESCE(J.FINAL_AMOUNT, 0) END), 0) AS Final_Compensation_Disbursed_Amount,
        COUNT(CASE WHEN J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('C', 'CO') THEN 1 END) AS Final_Compensation_No_of_cases_awarded,
        COALESCE(SUM(CASE WHEN J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('C', 'CO') THEN COALESCE(J.FINAL_AMOUNT, 0) END), 0) AS Final_Compensation_awarded_Amount,
        COUNT(CASE WHEN J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('E', 'S', 'F1') THEN 1 END) AS Final_Compensation_No_of_cases_Pending,
        COALESCE(SUM(CASE WHEN J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('E', 'S', 'F1') THEN COALESCE(J.FINAL_AMOUNT, 0) END), 0) AS Final_Compensation_Pending_Amount,
        COUNT(CASE WHEN O.CHARGE_SHEET_YES_NO = 'Yes' THEN 1 END) AS No_of_Chargesheet_filed,
        COUNT(CASE WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND J.INTERIM_AWARDED_YES = 'Yes' AND S.PROCEED_INTERIM IS NOT NULL THEN 1 END) AS Disbursed1,
        COUNT(CASE WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND J.INTERIM_AWARDED_YES = 'No' AND S.PROCEED_INTERIM IS NOT NULL THEN 1 END) AS Pending1,
        COUNT(CASE WHEN O.WILLINGNESS_COMPENSATION = 'Yes' OR J.INTERIM_AWARDED_YES = 'Yes' AND S.PROCEED_INTERIM IS NOT NULL THEN 1 END) AS Not_applicable,
        COUNT(CASE WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND S.PROCEED_FINAL IS NOT NULL THEN 1 END) AS Disbursed2,
        COUNT(CASE WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND S.PROCEED_FINAL IS NULL THEN 1 END) AS Pending2,
        COUNT(CASE WHEN J.FINAL IS NOT NULL THEN 1 END) AS Disposed3,
        COUNT(CASE WHEN J.FINAL IS NULL THEN 1 END) AS Pending3
    FROM 
        TNEGA_OVERALL_T_DUP O
    JOIN 
        TNEGA_JUDGE_LOGIN_T J ON O.ID = J.COURT_ID
    JOIN 
        TNEA_SUPERINTENDENT_T S ON O.ID = S.COURT_ID
    GROUP BY 
        O.DISTRICT_NAME
    ORDER BY 
        1 ASC
) A;

-- When click on district name it move to another page:

SELECT 
    ROW_NUMBER() OVER (ORDER BY A.DISTRICT_NAME) AS ROWNUM,
    A.*, 
    ROUND(
        COALESCE(
            (A."No_of_cases_Convicted" / NULLIF(A."Final_Compensation_No_of_cases_awarded", 0) * 100), 
            0
        ), 
        2
    ) AS "Conviction_rate",
    (COALESCE(A."Interim_Compensation_Pending_Amount", 0) + COALESCE(A."Final_Compensation_Pending_Amount", 0)) AS TOTAL
FROM (
    SELECT DISTINCT
        OT.DISTRICT_NAME,
        OT.POL_STAT,
        (SELECT COUNT(*) 
         FROM TNEGA_OVERALL_T_DUP O 
         WHERE O.DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT AND WILLINGNESS_COMPENSATION = 'Yes') AS WILLINGNESS_COMPENSATION,
        (SELECT COUNT(*) 
         FROM TNEGA_OVERALL_T_DUP O 
         WHERE O.DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "No_of_POCSO_cases_filed",
        (SELECT COUNT(*) 
         FROM TNEGA_OVERALL_T_DUP O 
         WHERE O.REQUEST_STATUS IN ('E', 'S', 'F1') AND O.DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Case_Status_Pending",
        (SELECT COUNT(*) 
         FROM TNEGA_OVERALL_T_DUP O 
         WHERE O.REQUEST_STATUS IN ('CO', 'C') AND O.DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Case_Status_Completed",
        COALESCE((SELECT COUNT(*) 
                  FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O 
                  WHERE J.JUDGEMENT = 'Acquittal' AND O.ID = J.COURT_ID AND O.POL_STAT = OT.POL_STAT AND DISTRICT_NAME = OT.DISTRICT_NAME 
                  GROUP BY DISTRICT_NAME), 0) AS "No_of_cases_Acquitted",
        COALESCE((SELECT COUNT(*) 
                  FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O 
                  WHERE TRIM(J.JUDGEMENT) = 'Convicted' AND O.ID = J.COURT_ID AND DISTRICT_NAME = O.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT), 0) AS "No_of_cases_Convicted",
        (SELECT COUNT(*) 
         FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O 
         WHERE TRIM(J.JUDGEMENT) = 'Others' AND O.ID = J.COURT_ID AND DISTRICT_NAME = O.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Other_Disposals",
        (SELECT COUNT(*) 
         FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O 
         WHERE J.TYPE = 'Interim Compensation' AND O.REQUEST_STATUS IN ('S') AND O.ID = J.COURT_ID 
         AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Interim_Compensation_No_of_cases_awarded",
        (SELECT COALESCE(SUM(J.INTERIM_AMOUNT), 0) 
         FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O 
         WHERE J.TYPE = 'Interim Compensation' AND O.REQUEST_STATUS IN ('S') AND O.ID = J.COURT_ID 
         AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Interim_Compensation_awarded_Amount",
        (SELECT COUNT(*) 
         FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O 
         WHERE J.TYPE = 'Interim Compensation' AND O.REQUEST_STATUS IN ('CO') AND O.ID = J.COURT_ID 
         AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Interim_Compensation_No_of_cases_Disbursed",
        (SELECT COALESCE(SUM(J.INTERIM_AMOUNT), 0) 
         FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O 
         WHERE J.TYPE = 'Interim Compensation' AND O.REQUEST_STATUS IN ('CO') AND O.ID = J.COURT_ID 
         AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Interim_Compensation_Disbursed_Amount",
        (SELECT COUNT(*) 
         FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O 
         WHERE J.TYPE = 'Interim Compensation' AND O.REQUEST_STATUS IN ('E', 'S', 'F1', 'C') 
         AND O.ID = J.COURT_ID AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Interim_Compensation_No_of_cases_Pending",
        (SELECT COALESCE(SUM(J.INTERIM_AMOUNT), 0) 
         FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O 
         WHERE J.TYPE = 'Interim Compensation' AND O.REQUEST_STATUS IN ('E', 'S', 'F1', 'C') 
         AND O.ID = J.COURT_ID AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Interim_Compensation_Pending_Amount",
        (SELECT COUNT(*) 
         FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O 
         WHERE J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('CO') AND O.ID = J.COURT_ID 
         AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Final_Compensation_No_of_cases_Disbursed",
        (SELECT COALESCE(SUM(J.FINAL_AMOUNT), 0) 
         FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O 
         WHERE J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('CO') AND O.ID = J.COURT_ID 
         AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Final_Compensation_Disbursed_Amount",
        (SELECT COUNT(*) 
         FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O 
         WHERE J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('C') AND O.ID = J.COURT_ID 
         AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Final_Compensation_No_of_cases_awarded",
        (SELECT COALESCE(SUM(J.FINAL_AMOUNT), 0) 
         FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O 
         WHERE J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('C') AND O.ID = J.COURT_ID 
         AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Final_Compensation_awarded_Amount",
        (SELECT COUNT(*) 
         FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O 
         WHERE J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('E', 'S', 'F1', 'C') AND O.ID = J.COURT_ID 
         AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Final_Compensation_No_of_cases_Pending",
        (SELECT COALESCE(SUM(J.FINAL_AMOUNT), 0) 
         FROM TNEGA_JUDGE_LOGIN_T J, TNEGA_OVERALL_T_DUP O 
         WHERE J.TYPE = 'Final Compensation' AND O.REQUEST_STATUS IN ('E', 'S', 'F1', 'C') AND O.ID = J.COURT_ID 
         AND DISTRICT_NAME = OT.DISTRICT_NAME AND O.POL_STAT = OT.POL_STAT) AS "Final_Compensation_Pending_Amount",
        (SELECT COUNT(*) 
         FROM TNEGA_OVERALL_T_DUP 
         WHERE CHARGE_SHEET_YES_NO IN ('Yes') AND DISTRICT_NAME = OT.DISTRICT_NAME AND POL_STAT = OT.POL_STAT) AS "No_of_Chargesheet_filed"
    FROM TNEGA_OVERALL_T_DUP OT
    ORDER BY 1 ASC
) A
WHERE A.DISTRICT_NAME = :P52_DISTRICT_NAME;


--When click on policice station name, it move to another report:
SELECT 
    OT.ID,
    OT.POL_STAT,
    OT.FIR_NO,
    OT.DATE_OF_FIR,
    COALESCE(TO_CHAR(OT.CHARGE_SHEET_DATE, 'DD-MON-YYYY'), '-') AS CHARGE_SHEET_DATE,
    OT.COMPLAINT_MADE,
    OT.COMPLAINT_NAME,
    (CASE 
        WHEN TJLT.COURT_FILE_DATE IS NOT NULL THEN 'Yes'
        ELSE 'No'
    END) AS "Chargesheet filled Status",
    TJLT.ORDER_NO,
    TJLT.COURT_FILE_DATE,
    CASE OT.REQUEST_STATUS
        WHEN 'E' THEN 'Pending'
        WHEN 'S' THEN 'Pending'
        WHEN 'F1' THEN 'Pending'
        WHEN 'C' THEN 'Pending'
        WHEN 'CO' THEN 'Disbursed'
    END AS STATUS,
    TJLT.JUDGEMENT,
    TJLT.INTERIM_AMOUNT,
    CASE OT.REQUEST_STATUS
        WHEN 'E' THEN 'Pending'
        WHEN 'S' THEN 'Pending'
        WHEN 'F1' THEN 'Pending'
        WHEN 'C' THEN 'Pending'
        WHEN 'CO' THEN 'Disbursed'
    END AS INTERIM_STATUS,
    TJLT.FINAL_AMOUNT,
    CASE OT.REQUEST_STATUS
        WHEN 'E' THEN 'Pending'
        WHEN 'S' THEN 'Pending'
        WHEN 'F1' THEN 'Pending'
        WHEN 'C' THEN 'Pending'
        WHEN 'CO' THEN 'Disbursed'
    END AS FINAL_STATUS,
    CASE 
        WHEN OT.DATE_OF_FIR IS NOT NULL AND TJLT.final_order_date IS NOT NULL THEN 
            DATE_PART('day', OT.DATE_OF_FIR - TJLT.final_order_date)
        ELSE 0
    END AS Aging_of_cases,
    CASE 
        WHEN OT.CHARGE_SHEET_DATE IS NOT NULL AND TJLT.final_order_date IS NOT NULL THEN 
            DATE_PART('day', OT.CHARGE_SHEET_DATE - TJLT.final_order_date)
        ELSE 0
    END AS Aging_of_chargesheet_date
FROM 
    TNEGA_OVERALL_T_DUP OT
JOIN 
    TNEGA_JUDGE_LOGIN_T TJLT 
ON 
    TJLT.COURT_ID = OT.ID
WHERE 
    OT.POL_STAT = :P63_POLICE;




-- 2. Report:

-- Yearwise Registered / Disposed
SELECT 
    TO_CHAR(OT.DATE_OF_FIR, 'YYYY') AS "Year",
    SUM(CASE WHEN REQUEST_STATUS IN ('E','S','F1') THEN 1 ELSE 0 END) AS "Registered",
    SUM(CASE WHEN REQUEST_STATUS IN ('C','CO') THEN 1 ELSE 0 END) AS "Disposed"
FROM 
    TNEGA_OVERALL_T_dup OT
GROUP BY 
    TO_CHAR(OT.DATE_OF_FIR, 'YYYY')
ORDER BY 
    TO_CHAR(OT.DATE_OF_FIR, 'YYYY');


-- Yearwise	 Acquittal', 'Convicted'
SELECT 
    TO_CHAR(OT.DATE_OF_FIR, 'YYYY') AS "Year",
    SUM(CASE WHEN J.JUDGEMENT = 'Acquittal' THEN 1 ELSE 0 END) AS Acquitted,
    SUM(CASE WHEN J.JUDGEMENT = 'Convicted' THEN 1 ELSE 0 END) AS Convicted,
    SUM(CASE WHEN J.JUDGEMENT = 'Others' THEN 1 ELSE 0 END) AS Others,
    SUM(CASE WHEN J.JUDGEMENT IN ('Acquittal', 'Convicted', 'Others') THEN 1 ELSE 0 END) AS Total
FROM 
    TNEGA_OVERALL_T_dup OT
JOIN 
    TNEGA_JUDGE_LOGIN_T J ON OT.ID = J.COURT_ID
GROUP BY 
    TO_CHAR(OT.DATE_OF_FIR, 'YYYY')
ORDER BY 
    TO_CHAR(OT.DATE_OF_FIR, 'YYYY');


-- District wise FIR  Registerd / Disposed:

/*SELECT 
    S.DISTRICT_NAME,
    SUM(CASE WHEN REQUEST_STATUS IN ('E','S','F1') THEN 1 ELSE 0 END) AS "Registered",
    SUM(CASE WHEN REQUEST_STATUS IN ('C','CO') THEN 1 ELSE 0 END) AS "Disposed"
FROM 
    TNEGA_OVERALL_T_dup OT RIGHT JOIN signup_t S
ON 
    OT.DISTRICT_NAME = S.DISTRICT_NAME
WHERE S.DISTRICT_NAME IS NOT NUll AND S.DISTRICT_NAME NOT IN ( 'District', 'State')
AND S.STATUS = 'Y'
GROUP BY 
    S.DISTRICT_NAME
ORDER BY 1 ASC;	*/


SELECT DISTINCT 
    S.DISTRICT_NAME,
    (SELECT COALESCE(SUM(CASE WHEN REQUEST_STATUS IN ('E', 'S', 'F1') THEN 1 ELSE 0 END), 0) 
     FROM TNEGA_OVERALL_T_dup 
     WHERE DISTRICT_NAME = S.DISTRICT_NAME) AS "Registered",
    (SELECT COALESCE(SUM(CASE WHEN REQUEST_STATUS IN ('C', 'CO') THEN 1 ELSE 0 END), 0) 
     FROM TNEGA_OVERALL_T_dup 
     WHERE DISTRICT_NAME = S.DISTRICT_NAME) AS "Disposed"
FROM 
    SIGNUP_T S
WHERE 
    S.DISTRICT_NAME IS NOT NULL
    AND S.DISTRICT_NAME NOT IN ('State', 'District', 'Directorate')
ORDER BY 
    S.DISTRICT_NAME ASC;




-- District wise Aquicted/ Convicted:
/* SELECT 
    S.DISTRICT_NAME,
    SUM(CASE WHEN J.JUDGEMENT = 'Acquittal' THEN 1 ELSE 0 END) AS Acquitted,
    SUM(CASE WHEN J.JUDGEMENT = 'Convicted' THEN 1 ELSE 0 END) AS Convicted,
    SUM(CASE WHEN J.JUDGEMENT IN ('Acquittal', 'Convicted') THEN 1 ELSE 0 END) AS Total
FROM 
    TNEGA_OVERALL_T_dup OT JOIN 
    TNEGA_JUDGE_LOGIN_T J ON OT.ID = J.COURT_ID RIGHT JOIN signup_t S
                          ON OT.DISTRICT_NAME = S.DISTRICT_NAME
WHERE S.DISTRICT_NAME IS NOT NUll AND S.DISTRICT_NAME NOT IN ( 'District', 'State')
AND S.STATUS = 'Y'
GROUP BY 
    S.DISTRICT_NAME
ORDER BY 1 ASC; 


SELECT 
    OT.DISTRICT_NAME,
    SUM(CASE WHEN J.JUDGEMENT = 'Acquittal' THEN 1 ELSE 0 END) AS Acquitted,
    SUM(CASE WHEN J.JUDGEMENT = 'Convicted' THEN 1 ELSE 0 END) AS Convicted,
    SUM(CASE WHEN J.JUDGEMENT IN ('Acquittal', 'Convicted') THEN 1 ELSE 0 END) AS Total
FROM 
    TNEGA_OVERALL_T_dup OT JOIN 
    TNEGA_JUDGE_LOGIN_T J ON OT.ID = J.COURT_ID
GROUP BY 
    OT.DISTRICT_NAME
ORDER BY 1 ASC; */
SELECT DISTINCT 
    S.DISTRICT_NAME,
    (SELECT COALESCE(SUM(CASE WHEN J.JUDGEMENT = 'Acquittal' THEN 1 ELSE 0 END), 0) 
     FROM TNEGA_OVERALL_T_dup OT, TNEGA_JUDGE_LOGIN_T J 
     WHERE OT.ID = J.COURT_ID AND OT.DISTRICT_NAME = S.DISTRICT_NAME) AS Acquitted,
    (SELECT COALESCE(SUM(CASE WHEN J.JUDGEMENT = 'Convicted' THEN 1 ELSE 0 END), 0) 
     FROM TNEGA_OVERALL_T_dup OT, TNEGA_JUDGE_LOGIN_T J 
     WHERE OT.ID = J.COURT_ID AND OT.DISTRICT_NAME = S.DISTRICT_NAME) AS Convicted,
    (SELECT COALESCE(SUM(CASE WHEN J.JUDGEMENT = 'Others' THEN 1 ELSE 0 END), 0) 
     FROM TNEGA_OVERALL_T_dup OT, TNEGA_JUDGE_LOGIN_T J 
     WHERE OT.ID = J.COURT_ID AND OT.DISTRICT_NAME = S.DISTRICT_NAME) AS Others,
    (SELECT COALESCE(SUM(CASE WHEN J.JUDGEMENT IN ('Acquittal', 'Convicted', 'Others') THEN 1 ELSE 0 END), 0) 
     FROM TNEGA_OVERALL_T_dup OT, TNEGA_JUDGE_LOGIN_T J 
     WHERE OT.ID = J.COURT_ID AND OT.DISTRICT_NAME = S.DISTRICT_NAME) AS Total
FROM 
    SIGNUP_T S
WHERE 
    S.DISTRICT_NAME IS NOT NULL
    AND S.DISTRICT_NAME NOT IN ('State', 'District', 'Directorate')
ORDER BY 
    S.DISTRICT_NAME ASC;

SELECT * FROM SIGNUP_T;


-- Customize Report:
SELECT 
    O.ID,
    O.DISTRICT_NAME,
    O.POL_STAT,
    O.CHILD_GENDER,
    O.NAME_MEDICAL_INSTITUTION,
    O.COMPLAINT_MADE,
    O.DATE_REQUISITION_MEDICAL_EXAMINATION,
    O.DATE_OF_MEDICAL_EXAMINATION_VICTIM,
    O.DATE_OF_INTERIM,
    O.COMPLAINT_NAME,
    O.DATE_OF_FIR,
    O.FIR_NO,
    C.COURT_FILE_DATE,
    C.INTERIM_AWARDED_YES,
    C.INTERIM,
    C.FINAL,
    O.COMPLAINT_COPY_MIMETYPE,
    O.COMPLAINT_COPY_FILENAME,
    O.NAME_PARENT,
    O.WILLINGNESS_COMPENSATION,
    COALESCE(O.WHO_NAME, '-') AS WHO_NAME,
    COALESCE(O.WHO_RELATIONSHIP, '-') AS WHO_RELATIONSHIP,
    COALESCE(TO_CHAR(O.WHO_DATE, 'DD-Mon-YYYY'), '-') AS WHO_DATE,
    COALESCE(O.ACCOUNT_NUMBER, '-') AS ACCOUNT_NUMBER,
    COALESCE(O.BANK_NAME, '-') AS BANK_NAME,
    COALESCE(O.BRANCH_NAME, '-') AS BRANCH_NAME,
    COALESCE(O.ACCOUNT_HOLDER_NAME, '-') AS ACCOUNT_HOLDER_NAME,
    COALESCE(O.IFSC_CODE, '-') AS IFSC_CODE,
    C.ORDER_NO,
    O.CHARGE_SHEET_YES_NO,
    COALESCE(TO_CHAR(O.CHARGE_SHEET_DATE, 'DD-Mon-YYYY'), '-') AS CHARGE_SHEET_DATE,
    C.INTERIM_ORDER_DATE,
    C.FINAL_AMOUNT,
    C.INTERIM_AMOUNT,
    C.FINAL_ORDER_DATE,
    C.JUDGEMENT,
    CASE 
        WHEN O.REQUEST_STATUS = 'CO' THEN 'Disposed'
        WHEN O.REQUEST_STATUS IN ('E', 'S', 'F1') THEN 'Pending'
        WHEN O.REQUEST_STATUS = 'C' THEN 'Disposed'
    END AS Payment_Status,
    (CURRENT_DATE - O.CHARGE_SHEET_DATE) AS DURATION,
    C.NAME_OF_COURT,
    O.INTERIM_YES,
    O.FINAL_YES,
    '<span aria-hidden="true" class="fa fa-download-alt"></span>' AS COPY,
    '<span aria-hidden="true" class="fa fa-download-alt"></span>' AS FIR,
    '<span aria-hidden="true" class="fa fa-download-alt"></span>' AS INTERIM,
    '<span aria-hidden="true" class="fa fa-download-alt"></span>' AS FINAL,
    CASE
        WHEN O.WILLINGNESS_COMPENSATION = 'No' THEN 'Not awarded'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AMOUNT IS NOT NULL AND S.PROCEED_INTERIM IS NULL THEN 'Pending'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND C.INTERIM_AMOUNT IS NOT NULL AND S.PROCEED_INTERIM IS NOT NULL THEN 'Disbursed'
        ELSE 'Other Condition'
    END AS Condition_Status,
    CASE
        WHEN C.FINAL IS NOT NULL THEN 'Orders passed'
        WHEN C.FINAL IS NULL THEN 'Pending Trail'
        ELSE 'Other Condition'
    END AS Condition_Status_1,
    CASE
        WHEN O.WILLINGNESS_COMPENSATION = 'No' THEN 'Not awarded'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND S.PROCEED_FINAL IS NULL THEN 'Pending'
        WHEN O.WILLINGNESS_COMPENSATION = 'Yes' AND S.PROCEED_FINAL IS NOT NULL THEN 'Disbursed'
        ELSE 'Other Condition'
    END AS Condition_Status_2,
    DATE_PART('day', CURRENT_DATE - O.DATE_OF_FIR) AS Aging_of_cases,
    DATE_PART('day', O.CHARGE_SHEET_DATE - O.DATE_OF_FIR) AS Aging_of_chargesheet_date
FROM 
    TNEGA_OVERALL_T_DUP O
JOIN 
    TNEGA_JUDGE_LOGIN_T C ON O.ID = C.COURT_ID
JOIN 
    TNEA_SUPERINTENDENT_T S ON O.ID = S.COURT_ID 
WHERE 
    O.REQUEST_STATUS IN ('C', 'CO', 'E', 'S', 'F1')
    AND (O.COMPLAINT_NAME BETWEEN COALESCE($4, O.COMPLAINT_NAME) AND COALESCE($5, O.COMPLAINT_NAME) OR O.COMPLAINT_NAME IS NULL)
    AND (O.DATE_OF_FIR BETWEEN COALESCE($2, O.DATE_OF_FIR) AND COALESCE($3, O.DATE_OF_FIR) OR O.DATE_OF_FIR IS NULL)
    AND (O.CHARGE_SHEET_DATE BETWEEN COALESCE($1, O.CHARGE_SHEET_DATE) AND COALESCE($6, O.CHARGE_SHEET_DATE) OR O.CHARGE_SHEET_DATE IS NULL)
    AND (C.INTERIM_ORDER_DATE BETWEEN COALESCE($7, C.INTERIM_ORDER_DATE) AND COALESCE($8, C.INTERIM_ORDER_DATE) OR C.INTERIM_ORDER_DATE IS NULL)
    AND (C.FINAL_ORDER_DATE BETWEEN COALESCE($9, C.FINAL_ORDER_DATE) AND COALESCE($10, C.FINAL_ORDER_DATE) OR C.FINAL_ORDER_DATE IS NULL)
    AND (C.COURT_FILE_DATE BETWEEN COALESCE($11, C.COURT_FILE_DATE) AND COALESCE($12, C.COURT_FILE_DATE) OR C.COURT_FILE_DATE IS NULL);

